### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by MrRorls12** [valadaptive/ntsc-rs#104]
the application is not starting, when I open it. I've tried running as admin, uninstalling, reinstalling, etc, just doesn't work.

**Comment by valadaptive** [comment]
What do you mean "installing"? There's no installer.

Have you tried running the ntsc-rs-standalone file from the `bin` folder directly?

**Comment by Degamisu** [comment]
I think I know your issue. If this is your first time running the app, it takes a long time to start. Give it time, I had that happen to me. It took it around 7 - 10 mins to startup, after that it will start in like 3 or 4 seconds.

**Comment by MrRorls12** [comment]
> What do you mean "installing"? There's no installer.
> 
> Have you tried running the ntsc-rs-standalone file from the `bin` folder directly?

i meant double-clicking, im kind of an idiot

**Comment by MrRorls12** [comment]
> I think I know your issue. If this is your first time running the app, it takes a long time to start. Give it time, I had that happen to me. It took it around 7 - 10 mins to startup, after that it will start in like 3 or 4 seconds.

it doesn't even open

**Comment by valadaptive** [comment]
Have you extracted all the files from the .zip?

**Comment by Degamisu** [comment]
@valadaptive i think a logging system would help a lot. we could track the issues that way.

**Comment by MrRorls12** [comment]
> Have you extracted all the files from the .zip?

yes

**Comment by MrRorls12** [comment]
> What do you mean "installing"? There's no installer.
> 
> Have you tried running the ntsc-rs-standalone file from the `bin` folder directly?

yes

> I think I know your issue. If this is your first time running the app, it takes a long time to start. Give it time, I had that happen to me. It took it around 7 - 10 mins to startup, after that it will start in like 3 or 4 seconds.

it doesn't even open, i just double click and nothing

**Comment by valadaptive** [comment]
Can you post a screen recording of you trying to open the application?

**Comment by MrRorls12** [comment]
https://github.com/valadaptive/ntsc-rs/assets/113948883/49844907-65ee-4239-ada4-259fe4be9d3d

here

**Comment by valadaptive** [comment]
Sorry for the delay in responding.

That video seems to show you opening ntsc-rs-launcher and not ntsc-rs-standalone. Can you post a video of you trying to open ntsc-rs-standalone in the `bin` folder?

**Comment by MrRorls12** [comment]
> Sorry for the delay in responding.
> 
> That video seems to show you opening ntsc-rs-launcher and not ntsc-rs-standalone. Can you post a video of you trying to open ntsc-rs-standalone in the `bin` folder?

The exact same thing happens.

**Comment by EnzoHub2024** [comment]
So, it wasn't loading it on a bin folder. Can you fix this for me, @valadaptive?

**Comment by Z3M1R11P** [comment]
were you able to solve it? I have the same problem

**Comment by valadaptive** [comment]
For those having trouble opening ntsc-rs: can you go to **Settings > System > Display > Advanced display settings** (below the "Multiple displays" section) and tell me **what model of graphics card you have**?

ntsc-rs requires a working GPU, and some older Intel integrated GPUs aren't supported on Windows 10. If that's the case, I can try to prioritize getting another solution working.

**Comment by valadaptive** [comment]
Please re-read the above message carefully. I need to know **what model of graphics card** you have.

**Comment by Z3M1R11P** [comment]
> Para aquellos que tienen problemas para abrir ntsc-rs: ¿pueden ir a **Configuración > Sistema > Pantalla > Configuración de pantalla avanzada** (debajo de la sección "Varias pantallas") y decirme **qué modelo de tarjeta gráfica tienen** ?
> 
> ntsc-rs requiere una GPU que funcione, y algunas GPU integradas Intel más antiguas no son compatibles con Windows 10. Si ese es el caso, puedo intentar priorizar que funcione otra solución.

I have a Mobile Intel(R) 4 Series Express Chipset Family (Microsoft Corporation - WDDM 1.1)

**Comment by valadaptive** [comment]
I'm going to track this type of bug (ntsc-rs not starting if you don't have a working graphics card) in #147.
