### ISSUE TITLE
Linux version does not launch properly

### ISSUE THREAD

**Issue by 0x5066** [valadaptive/ntsc-rs#109]
The Linux version of ntsc-rs does not launch properly, all I'm getting is a blank grey window that's bigger than both of my screens combined, on the other hand, the Windows version through Wine launches with no issues whatsoever.

There are no logs provided when launched through the terminal, I'm running EndeavourOS.
I'm not sure what else is needed for Linux reports

**Comment by valadaptive** [comment]
Do you have GStreamer installed?

**Comment by 0x5066** [comment]
I have GStreamer installed, not any of the other variants

**Comment by valadaptive** [comment]
What do you mean "variants"? The additional GStreamer packages contain codecs and other plugins for GStreamer that are necessary to load various video formats.

If you resize the window to fit your screen, is there a loading spinner or anything that could be hidden by the window's size, or is it completely blank?

**Comment by 0x5066** [comment]
With variants I mean things like gstreamer0.10-good and so on.

There's nothing, and trying to close it just calls the "This window might be busy and is not responding" window
![image](https://github.com/valadaptive/ntsc-rs/assets/38136789/2557b286-5959-47a4-a01e-949a0aab2c73)

**Comment by valadaptive** [comment]
Yeah, those are the actual plugins for GStreamer.

Is there a gstreamer1-* set of packages? The 0.10 series may be too old for ntsc-rs to function properly.

**Comment by 0x5066** [comment]
None in the Arch repos or AUR
The gstreamer package that is installed is version 1.24.3-1

**Comment by valadaptive** [comment]
Try installing gst-plugins-base, gst-plugins-good, gst-plugins-bad, and gst-plugins-ugly.

If that doesn't work, perhaps try building it from source with [rustup](https://rustup.rs/)? It should be a lot easier on Linux than on Windows.

**Comment by 0x5066** [comment]
I ran the git command, recompiled and I'm at the same grey window that's unresponsive

**Comment by Degamisu** [comment]
Hey! have you tried this script yet?

```bash
$ sudo apt-get install libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-alsa
```

What version of linux are you using? ubuntu?

**Comment by 0x5066** [comment]
EndeavourOS, a flavor of Arch Linux

**Comment by valadaptive** [comment]
> Hey! have you tried this script yet?
> 
> ```shell
> $ sudo apt-get install libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-alsa
> ```
> 
> What version of linux are you using? ubuntu?

They stated in the very top post that they are using EndeavourOS, which does not use the APT package manager, and responded earlier that they have installed all GStreamer plugins. I appreciate your enthusiasm to help, but don't feel obligated to respond to every issue or solve everyone's problems--it seems like you've been taking on more of a "backseat repository manager" role as of late.

**Comment by 0x5066** [comment]
![image](https://github.com/valadaptive/ntsc-rs/assets/38136789/a6c9055c-b7fb-47d7-8fe6-65db09876e77)
Hello World launches just fine

**Comment by valadaptive** [comment]
Since I don't have your system and can't reproduce it on my own, I'm not really sure what's going on. If you're adventurous, you could try manually commenting out bits of code in the standalone app (`crates/gui/src/app/main.rs`; the `run` function at line 140 and `update` function at line 2845 are good places to start) and trying to determine the cause of the hang that way.

**Comment by valadaptive** [comment]
Apologies for the delay--can you try running ntsc-rs with the `RUST_LOG=debug` environment variable set and see where it gets stuck?

**Comment by 0x5066** [comment]
Will try once I'm home

**Comment by 0x5066** [comment]
For kicks I thought to launch the program as is without any command line arguments or environment variables, just to see what would happen.
It now just launches.

![image](https://github.com/user-attachments/assets/60b070ac-4520-464f-92c6-8e67a0392a3a)

And it also processes videos just fine too...
![image](https://github.com/user-attachments/assets/3e50eb93-baba-4380-9bb0-a0dd9503e511)

No idea what you (or I) did, but it's working flawlessly now!
Thanks!

**Comment by valadaptive** [comment]
I updated a lot of dependencies for the 0.8.0 release, and it's possible that a bugfix in one of them fixed the issue. Glad to hear it's working now!
