### ISSUE TITLE
endless loading problem while the app is already open 

### ISSUE THREAD

**Issue by RedMations** [valadaptive/ntsc-rs#115]
i tried to open like three times, now it´s stuck the loading screen like endless loading. can you please fix it or shold i wait for fixed the loading screen while it already started opening the app. hopefully it helps i guess. thanks!

**Comment by RedMations** [comment]
or it just works hopefully.

**Comment by Degamisu** [comment]
It takes a while when you first download the app. Wait around 10 - 15 mins for it to set itself up. if this doesn't work, redownload the app. If that also doesn't work, it could be your hardware.

**Comment by RedMations** [comment]
i just works already that took like a minute ago now it works please close the issue when it´s fixed the issue

**Comment by RedMations** [comment]
on my pc is windows 11

**Comment by valadaptive** [comment]
Try leaving it open for, as @Degamisu suggested, 10-15 minutes.

**Comment by valadaptive** [comment]
Going to assume this is no longer an issue since there have been no updates since the beginning of June. Let me know if this is still an issue.
