### ISSUE TITLE
Suggestion: Stream from (and to?) pipewire

### ISSUE THREAD

**Issue by UltraBlackLinux** [valadaptive/ntsc-rs#119]
Hey there,
this is an awesome project, and I've really fallen in love with it, but the fact that you always have to either get an image or video file is a bit annoying. I think it would be really neat if you could live-stream a screen into ntsc-rs and then into a file or back into a video output within pipewire.
What do you think?
Thanks!

**Comment by valadaptive** [comment]
I've also heard some people ask about an OBS filter. The main issue I have with adding more and more APIs is that it adds a maintenance burden as I change the API surface. The After Effects and OpenFX plugins are already challenging enough to maintain--when I added support for interlaced rendering, a solid 2/3rds of the time was spent adding support to the plugins.

It seems like the best long-term solution would be getting these third-party solutions to support the OpenFX API, try to come up with another unified and stable API for real-time applications, or for someone to create a Rust-based VFX API wrapper library.

If someone else does want to create an ntsc-rs plugin for third-party APIs, I do expose a C API for that purpose.

**Comment by Degamisu** [comment]
> I've also heard some people ask about an OBS filter. The main issue I have with adding more and more APIs is that it adds a maintenance burden as I change the API surface. The After Effects and OpenFX plugins are already challenging enough to maintain--when I added support for interlaced rendering, a solid 2/3rds of the time was spent adding support to the plugins.
> 
> It seems like the best long-term solution would be getting these third-party solutions to support the OpenFX API, try to come up with another unified and stable API for real-time applications, or for someone to create a Rust-based VFX API wrapper library.
> 
> If someone else does want to create an ntsc-rs plugin for third-party APIs, I do expose a C API for that purpose.

A few months back I started working (and made a working plugin) that works with OBS, unfortunately, the Linux PC that I had this on died and I couldn't recover the software. The backup drive died along with it, but I am working on resurrecting it. So yes, an outdated version of NTSC-RS OBS does exist!
