### ISSUE TITLE
NTSC-RT Ultimate Preset Pack

### ISSUE THREAD

**Issue by polikux** [valadaptive/ntsc-rs#120]
# NTSC-RT Ultimate Preset Pack
**Howdy everyone**. I have been working on this project for some time and I am finally presenting this project to you _"NTSC-RT Ultimate Preset Pack"_. This is fan made a compilation of preset .json files, from various creators for the NTSC-RS program. Exactly for version v0.7.3. I made this compilation of presets to make it easier to use this great program, especially for beginners but also for more advanced users. 

I made a few of my own but also looked for some already available presets here to collect they all just for convenience. I'm going to develop this little project. This is the first edition of this project, so there are not many presets yet. So if you feel like it and have time, you can suggest new categories or send new presets. I will also be glad for helpful  corrections. Thanks in advance. I hope it will be useful :D. 
## Download
[NTSC-RT Ultimate Preset Pack V0.1.0.zip](https://github.com/user-attachments/files/15841342/NTSC-RT.Ultimate.Preset.Pack.V0.1.0.zip)

----
> [!NOTE]
> **_How to add a preset:_**
NTSC-RS the "Effect" tab has a button called "Load" in the lower left corner. Select the Preset you are interested in the file explorer and you're done.

## All categories of presets that I managed to include in this version for now:
- _Analog TV_
- _Camcorders VHS-C_
- _Capture Card_
- _RCA Connector_
- _VHS Tapes._

## Presets are from creators such as:

-  @Polikux
-  @Prankejten
-  @nerdgh0st
-  @oisintheblue
-  @Smfthe1199
-  @nlolnlolnlolnlo
-  @Degamisu
-  @valadaptive

----

<details><summary>My presets' appearance:</summary>
<p>

### Original:
![PM5544_with_non-PAL_signals](https://github.com/valadaptive/ntsc-rs/assets/100824173/5e48fa80-997e-44ad-b072-df45da74673c)
### Agribusiness:
![PM5544_with_non-PAL_signals_ntsc](https://github.com/valadaptive/ntsc-rs/assets/100824173/a18ce36f-b0e9-41d1-9337-e94c945de869)
### Announcements:
![2](https://github.com/valadaptive/ntsc-rs/assets/100824173/8e0fc6a5-6641-4b85-b925-05240ead7db2)
### Break:
![3](https://github.com/valadaptive/ntsc-rs/assets/100824173/5a1c21b6-b7be-47f3-b400-18f91b26d473)
### Catchdove:
![4](https://github.com/valadaptive/ntsc-rs/assets/100824173/ec61506e-fcbb-4b35-bfdf-de710e4b7e63)
### Stereophony:
![5](https://github.com/valadaptive/ntsc-rs/assets/100824173/7c0eca0f-a324-40f1-a4ac-58efc3432bf3)
### Supercops:
![6](https://github.com/valadaptive/ntsc-rs/assets/100824173/ab82710a-cb01-47eb-afc0-23ec5bf984f8)
### Test board:
![7](https://github.com/valadaptive/ntsc-rs/assets/100824173/e62240ff-1bd2-45bb-ab65-75521876c089)
### Winter evening:
![8](https://github.com/valadaptive/ntsc-rs/assets/100824173/a1709627-f71d-4751-81ac-eed9c527f23f)
### JVC GR-AXM230U
![9](https://github.com/valadaptive/ntsc-rs/assets/100824173/7e1c79b5-def9-4259-8985-32dea38296e2)
### Panasonic NV M1
![10](https://github.com/valadaptive/ntsc-rs/assets/100824173/27137c2d-1f26-457a-9ce8-97de7b595efd)

</p>
</details> 

----

> [!IMPORTANT]
> I warn you that there may be errors in categorizing Presets due to my inattention or a different way of thinking about a given preset. Remember that the name of a preset does not always have to indicate the category or use of a given .json file. Also, my native text is not English, so I apologize for any grammatical errors

**Comment by Degamisu** [comment]
wow! thank you for using one of my presets! this will be very useful.

**Comment by smfthe1199** [comment]
Wow! That is very ultimate, and it's a pleasure to create assets based on things that happen on old TVs/others. Great job and thanks in advance!

**Comment by fukionline** [comment]
awsum

**Comment by nelazstf** [comment]
Amazing but why's this on the issues tab tho

**Comment by emeraldsucksss** [comment]
This should be on the Discussions tab instead of the Issues tab, but holy shit this is so useful. Thank you

**Comment by smfthe1199** [comment]
> Wow! That is very ultimate, and it's a pleasure to create assets based on things that happen on old TVs/others. Great job and thanks in advance!

@polikux Can I update this project of yours?

**Comment by polikux** [comment]
> @polikux Can I update this project of yours?
@smfthe1199 Of course. If anything, if I update this I would move it to the "Discussions tab". Thanks for the support.

**Comment by smfthe1199** [comment]
> @smfthe1199 Of course. If anything, if I update this I would move it to the "Discussions tab". Thanks for the support.

I should suggest the README.txt has the changelogs moved to CHANGELOG.txt because I want the contents of the README.TXT file and the changelogs in there seperated to have some space, in addition to the changelogs being seperated in lists as well as the preset creators, what's your say?

**Comment by valadaptive** [comment]
Since updated versions of the Preset Pack have been moved to the Discussions tab, I'm going to close this issue

**Comment by ArianDv-ps** [comment]
thank u so much for sharing !!
