### ISSUE TITLE
Cannot load any images or videos anymore

### ISSUE THREAD

**Issue by BluesM18A1** [valadaptive/ntsc-rs#128]
This program used to work completely fine for me, but not today.
I'm running the standalone version on an Arch-based linux install so I wonder if it has to do with some undocumented dependency or an incompatible version of some library it depends on.

Any time I try to load any file, I get an error message at the top of the window that says 
 `Error loading video: Failed to find element factory with name 'autoaudiosink' for creating element`.
Why an audio-related error happens even when loading still images with no audio is beyond me, so I tried running the program with a terminal to see if I get more verbose error output, but the terminal gives bupkus.

I'd appreciate any clues as to what's going on under the hood.

**Comment by valadaptive** [comment]
You're probably missing some GStreamer plugins. Make sure you have gst-libav, gst-plugins-bad, gst-plugins-base, gst-plugins-good, and gst-plugins-ugly installed.

**Comment by BluesM18A1** [comment]
> You're probably missing some GStreamer plugins. Make sure you have gst-libav, gst-plugins-bad, gst-plugins-base, gst-plugins-good, and gst-plugins-ugly installed.

Hmm, I was almost certain the blanket "gstreamer" package in the official arch repositories installs all of these things automatically but it turns out I was missing gst-plugins-good while having everything else. Pretty odd but that has solved the issue, thanks!
