### ISSUE TITLE
OFX version issue: "checkerboards" in color bleed/offsets

### ISSUE THREAD

**Issue by Lu9-ST** [valadaptive/ntsc-rs#13]
Maybe it is an issue with the OFX version or maybe specifically VEGAS Pro which is what I'm using, can't quite tell. But I was trying out the plugin on VEGAS and at least on preview (with the preview quality set to the best one) it looks exactly as I expect, nothing wrong here. But if I render the video out, or even just copy a frame of the video or save a frame to an image (buttons that are in the preview panel) there will be this pretty weird artifact that I'm not sure what it is - here is a close-up on it:
![image](https://github.com/valadaptive/ntsc-rs/assets/16146042/833ab871-b6fe-44c6-81af-78c5127971e2)
I thought it perhaps has something to do with the alpha channel but that doesn't make a lot of sense.
Maybe there is a setting in vegas itself that I don't know about that I could change that would fix this, but for now I'll just ask about it in case any of you might know what the issue is.

Also: dunno if this is something you could even fix, but if video preview is set to lower resolutions (i.e. "Good (Auto)" or "Preview (Quarter)") that also affects the effect in the preview, so to get an actual preview of how the end result will look like I have to temporarily switch video preview to full resolution ("Good (Full)" or "Best (Full)") which isn't the worst thing ever or makes it unusable, but it Would be nice if the effect preview stayed a bit consistent

**Comment by valadaptive** [comment]
The checkerboard pattern is intentional--it's [an NTSC/VHS artifact called "dot crawl"](https://en.wikipedia.org/wiki/Dot_crawl). You may be able to change (but not eliminate) the pattern by changing the "Chroma demodulation filter" to "1-line comb" or "2-line comb".

Regarding the video preview, I don't think I can fix that. Vegas gives the plugin a low-resolution image to work with, and the plugin gives a low-resolution image back.

**Comment by Lu9-ST** [comment]
ah, I thought it wasn't the dot crawl because of how... uniform and "perfectly checkered" it looks, but good to know. also just checked that it also happens on the standalone version, so maybe i just didn't notice it much with other videos i've tested it with
