### ISSUE TITLE
A simple keyframing system for standalone version.

### ISSUE THREAD

**Issue by oisintheblue** [valadaptive/ntsc-rs#134]
It would be nice to not be limited to only using the OFX/AFX versions if we want something in the effect to change at a certain point. 
here's a poorly drawn concept.
![image](https://github.com/user-attachments/assets/8ce45458-688e-4a25-874d-5e858d191cae)
no, this does not mean "turn ntsc-rs into a whole video editor!", just a simple keyframing system or smth like that, nothing else.

**Comment by oisintheblue** [comment]
forgot that the timeline thingy already exists, but only for videos or gifs. oops

**Comment by valadaptive** [comment]
This was [previously suggested](https://github.com/valadaptive/ntsc-rs/issues/67), and I don't want to implement it if I can avoid it.

I do want to make video editing software in the future, but I don't want to slowly turn ntsc-rs into half-baked video editing software. I'm already running up against the limits of GStreamer, the underlying video library. Even updating the preview when it's paused seems to be outside the scope of what they intend to support, and I had to hack it in.

Rewriting ntsc-rs to the point where any sort of advanced video editing features would be supported would be a pretty large undertaking, to the point where it would probably be easier to start from scratch and develop "real" video editing software in the first place.
