### ISSUE TITLE
ofx plugin running in magix vegas has severely distorted colors

### ISSUE THREAD

**Issue by nlolnlolnlolnlo** [valadaptive/ntsc-rs#14]
tested using vegas pro 17.0

all options affecting the color of the output were disabled and adjusting the chroma phase error seemingly didn't help either

![Image3](https://github.com/valadaptive/ntsc-rs/assets/154479340/5220784e-36d2-44e4-a970-69a93ad10dad)
unaffected colors (generic vegas test card)

![Image2](https://github.com/valadaptive/ntsc-rs/assets/154479340/5d889055-45b2-4f61-9c6d-366c40f25e50)
test card after globally applying ntsc-rs under "video output fx", all video degradation settings set to minimum

from what i can tell, it seems the red/blue channels are being swapped? i'm not sure what would cause this.

**Comment by valadaptive** [comment]
This seems to be [an issue with Vegas 17 and up](https://old.reddit.com/r/VegasPro/comments/gqixyw/twixtor_inverts_my_colors_reds_turn_blue_blues/frt25k7), or possibly [an interaction with AMD graphics drivers](https://www.vegascreativesoftware.info/us/forum/vegas-pro-19-0-completly-different-colours-after-rendering-video--136578/). They *might've* fixed it in newer versions (of the driver or of Vegas; not sure). What version of Vegas are you running?

**Comment by valadaptive** [comment]
Going to close this issue; seems like a Vegas bug rather than an ntsc-rs bug.
