### ISSUE TITLE
Need help with 1980s vhs effect and 1980s tv effect

### ISSUE THREAD

**Issue by angryfrenchtoast** [valadaptive/ntsc-rs#143]
Can someone please tell me how to make a realistic 1980s tv broadcast effect and a 1980s vhs tape effect?
This is what i want the tv effect to look like: 

![image](https://github.com/user-attachments/assets/9ff48e18-756c-49b9-8450-687bd094b7d2)

This is what i want the vhs tape effect to look like: 

![image](https://github.com/user-attachments/assets/4cc2fdf5-4bcd-49a6-aa12-f7900d0a4a00)

**Comment by valadaptive** [comment]
These types of inquiries are better suited to the [Q&A section of the Discussions tab](https://github.com/valadaptive/ntsc-rs/discussions/categories/q-a).
