### ISSUE TITLE
App Not opening

### ISSUE THREAD

**Issue by nexuz911** [valadaptive/ntsc-rs#145]
i tried everything but nothing, cmd python and other things with no results, how can i fix it ?

**Comment by valadaptive** [comment]
What's your operating system? Is the window not even appearing, or does it show a loading screen?

**Comment by nexuz911** [comment]
> What's your operating system? Is the window not even appearing, or does it show a loading screen?

Windows 10 21H1 LTSC

**Comment by nexuz911** [comment]
> What's your operating system? Is the window not even appearing, or does it show a loading screen?

and window doesent show up

**Comment by valadaptive** [comment]
Make sure you've actually extracted all the files from the .zip, and you're not just trying to run it from inside the .zip.

If that still doesn't work, try running `ntsc-rs-standalone`, located in the `bin` folder.

**Comment by nexuz911** [comment]
> Make sure you've actually extracted all the files from the .zip, and you're not just trying to run it from inside the .zip.
> 
> If that still doesn't work, try running `ntsc-rs-standalone`, located in the `bin` folder.

did that like 40 times

**Comment by valadaptive** [comment]
Can you send a screenshot of the ntsc-rs application in the file manager?

**Comment by nexuz911** [comment]
> Can you send a screenshot of the ntsc-rs application in the file manager?

ok

**Comment by nexuz911** [comment]
> Can you send a screenshot of the ntsc-rs application in the file manager?

![Capture](https://github.com/user-attachments/assets/6578e81a-e3ba-437c-acc2-0e110248bc5e)

**Comment by nexuz911** [comment]
there

**Comment by valadaptive** [comment]
It looks like you're using Windows 7, which has [reached end-of-life and is no longer receiving security updates since 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962). ntsc-rs does not support Windows 7.

This is not unique to ntsc-rs; most software, including every major web browser, has also dropped support for Windows 7. I would strongly recommend upgrading to Windows 11, or Windows 10 if your computer doesn't support 11.

**Comment by nexuz911** [comment]
> It looks like you're using Windows 7, which has [reached end-of-life and is no longer receiving security updates since 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962). ntsc-rs does not support Windows 7.
> 
> This is not unique to ntsc-rs; most software, including every major web browser, has also dropped support for Windows 7. I would strongly recommend upgrading to Windows 11, or Windows 10 if your computer doesn't support 11.

its a theme, aero 10 look https://www.deviantart.com/vaporvance/art/Aero10-for-Windows-10-1903-22H2-909711949

**Comment by valadaptive** [comment]
Some older graphics cards don't have support for some things that ntsc-rs needs to run.

If you go to the Windows "Display" settings, scroll down to the bottom and click "Advanced display settings", then click "Display adapter properties for Display 1", it should open a window telling you what graphics card you have. Can you send a screenshot?

**Comment by nexuz911** [comment]
> Some older graphics cards don't have support for some things that ntsc-rs needs to run.
> 
> If you go to the Windows "Display" settings, scroll down to the bottom and click "Advanced display settings", then click "Display adapter properties for Display 1", it should open a window telling you what graphics card you have. Can you send a screenshot?
 look 

https://github.com/user-attachments/assets/74cc73bc-2385-4c3c-b206-c0b55fc444af

**Comment by nexuz911** [comment]
Hey @valadaptive are you there?

**Comment by valadaptive** [comment]
I maintain this software and respond to issues in my free time. Please don't expect any sort of live support.

[Try running this version](https://drive.proton.me/urls/D6J3Z4WK78#xGvoXD44wE7H), which should hopefully show an error dialog if it runs into an issue while opening.

**Comment by nexuz911** [comment]
> I maintain this software and respond to issues in my free time. Please don't expect any sort of live support.
> 
> [Try running this version](https://drive.proton.me/urls/D6J3Z4WK78#xGvoXD44wE7H), which should hopefully show an error dialog if it runs into an issue while opening.

aint working neither

**Comment by valadaptive** [comment]
OK, try downloading [this (somewhat old) debug build of ntsc-rs](https://drive.proton.me/urls/9W1Z8SH6P8#umSdL1dbIilc), and then run it in the Command Prompt thusly:

```
cd /d "C:/path/to/ntsc-rs-standalone-windows/bin"
SET RUST_BACKTRACE=full
ntsc-rs-standalone.exe
```

(make sure to run the *debug* version in the Command Prompt)

**Comment by valadaptive** [comment]
Also, can you post your full system specs? (right-click "Computer" in the file manager and click "Properties")

**Comment by nexuz911** [comment]
![Capture](https://github.com/user-attachments/assets/f7d20f83-5eac-4144-a25f-e8a3e8b0b19f)

**Comment by nexuz911** [comment]
@valadaptive it is not working

**Comment by valadaptive** [comment]
Are you sure this is Windows 10? That looks like the Windows 7 System Properties pane.

Did you get *any* error message of any sort printed to the Command Prompt when running the *debug* build that way?

**Comment by nexuz911** [comment]
no

**Comment by valadaptive** [comment]
Are you *sure* you're running the debug build that I uploaded?

**Comment by nexuz911** [comment]
btw look https://archive.org/details/teams10to7mod/Frame%206.png this is my os

**Comment by nexuz911** [comment]
> Are you *sure* you're running the debug build that I uploaded?

Yeah

**Comment by valadaptive** [comment]
OK, I'll try building another debug build

**Comment by nexuz911** [comment]
> OK, I'll try building another debug build

Thanks bud

**Comment by valadaptive** [comment]
After doing a bit of research, it appears that the Intel HD Graphics 2000 GPU in the i5-2400 doesn't support Windows 10, and ntsc-rs requires 3D acceleration.

You're not the first person to experience this compatibility issue, so I'll try to prioritize adding some sort of fallback renderer for the next major release.

**Comment by nexuz911** [comment]
> After doing a bit of research, it appears that the Intel HD Graphics 2000 GPU in the i5-2400 doesn't support Windows 10, and ntsc-rs requires 3D acceleration.
> 
> 
> 
> You're not the first person to experience this compatibility issue, so I'll try to prioritize adding some sort of fallback renderer for the next major release.

Do you want proof it runs on 10?

**Comment by valadaptive** [comment]
I thought the issue was that it *doesn't* run on 10.

**Comment by nexuz911** [comment]
> I thought the issue was that it *doesn't* run on 10.

Then what is it?, its a DELL Optiplex 790

**Comment by valadaptive** [comment]
From the archive.org link you posted, it appears to be a modified version of Windows 10 LTSB. The Intel HD Graphics 2000 drivers don't support that.

I'll try to acquire some older hardware and come up with a solution for the next version of ntsc-rs.

**Comment by nexuz911** [comment]
> From the archive.org link you posted, it appears to be a modified version of Windows 10 LTSB. The Intel HD Graphics 2000 drivers don't support that.
> 
> 
> 
> I'll try to acquire some older hardware and come up with a solution for the next version of ntsc-rs.

You're so dope man,thanks

**Comment by EnzoHub2024** [comment]
it doesn't open on windows 11.
