### ISSUE TITLE
"Load from JSON" should also be added in the Plugin version?

### ISSUE THREAD

**Issue by EsaiTheMartian2007** [valadaptive/ntsc-rs#159]
Can this feature be added to the Adobe/OpenFX plugin version of NTSC-RS?
![loadfrom](https://github.com/user-attachments/assets/39c93f83-b9bb-45ce-b0f6-d054c2aab7e3)

**Comment by valadaptive** [comment]
I only recently realized just how many presets people have made. I don't think there is an "official" way of opening file dialogs in either the After Effects or OpenFX APIs, and I don't know what complications may arise from doing so behind the application's back, but I can try to work on this.

**Comment by joman66** [comment]
Apologies for the duplicate submission. I promise I attempted to find this and was unsuccessful lol. Glad to see this requested feature now seen by the dev!

**Comment by valadaptive** [comment]
This has been added in v0.9.0!
