### ISSUE TITLE
Is it possible to use this as a shader for possibly Reshade?

### ISSUE THREAD

**Issue by oisintheblue** [valadaptive/ntsc-rs#16]

**Comment by valadaptive** [comment]
This doesn't execute on the GPU, so probably not. If there's a way to call into arbitrary CPU-side code from ReShade, the performance *should* be good enough for real-time, but it's not a shader.

I've thought about making a GLSL version for games, etc. but it would involve rewriting basically the entire image processing part, and it'd require about a dozen different shader passes.

**Comment by oisintheblue** [comment]
oh ok, thats understandable. what about simulating generation loss?

**Comment by valadaptive** [comment]
There's no way to simulate generation loss in the standalone app currently. You can do so with the OpenFX or AE plugin by simply applying the effect multiple times in succession, although each iteration will decrease performance.
