### ISSUE TITLE
Rolling tracking line

### ISSUE THREAD

**Issue by Porcupine2009** [valadaptive/ntsc-rs#183]
This is a feature suggestion, there should be a toggle for the rolling tracking line that appears on some vhs tapes

example:
![0909](https://github.com/user-attachments/assets/1e846fc2-cb03-4820-af45-07039ad45e1b)

that's about it.

**Comment by 0x5066** [comment]
From a quick google it doesn't seem like that's a real effect and it's probably something that somehow got popular because it makes it more "authentic"

**Comment by valadaptive** [comment]
> From a quick google it doesn't seem like that's a real effect and it's probably something that somehow got popular because it makes it more "authentic"

I'm inclined to agree with this. As far as I can tell, it originates in Red Giant Universe VHS.

At some point, I do want to revamp tracking noise, but that's a separate issue.

**Comment by Porcupine2009** [comment]
Alr, thanks for letting me know :)
