### ISSUE TITLE
Internal Data Stream Error when loading videos

### ISSUE THREAD

**Issue by wereretot** [valadaptive/ntsc-rs#185]
Anytime I try to load a mkv file that worked before, it now shows this error. I wish that it would actually explain the issue rather than throw a generic error message that tells me that the file isn't loading correctly.

**Comment by wereretot** [comment]
That's odd, the video file worked when I removed any blank space from the beginning of the video file.

**Comment by valadaptive** [comment]
Can you upload the video? The issue might be that it has a variable frame rate.

**Comment by wereretot** [comment]
@valadaptive I figured out something, interestingly AVI files always load and work.

**Comment by valadaptive** [comment]
Can you try v0.9.0 and check if the issue still occurs? If so, can you please upload one of the video files that fails to load so that I can reproduce the issue?

**Comment by valadaptive** [comment]
Closing due to a lack of activity or a way for me to reproduce the issue. v0.9.0 included some changes that may fix intermittent errors on Nvidia GPUs. Let me know if you keep experiencing issues.
