### ISSUE TITLE
macOS Premiere Pro plugin doesn't load (24.6.1)

### ISSUE THREAD

**Issue by Spritzerland** [valadaptive/ntsc-rs#190]
I downloaded the package file, and it installs the .plugin, but it doesn't load, as it's not showing up in the Effects panel.
<img width="1247" alt="Screenshot 2024-09-24 at 4 25 28 PM" src="https://github.com/user-attachments/assets/5c3215aa-a543-4192-aded-8a619829ea44">

I've already cleared the plugin cache, but it still doesn't load.

**Comment by valadaptive** [comment]
I can't reproduce this locally, but the plugin library I'm using did update something Premiere-related recently. Try [this version](https://drive.proton.me/urls/GBD5GD84XC#jlFwlVkSuMc5) and let me know if it works.

**Comment by Spritzerland** [comment]
This works! Thanks a lot!
