### ISSUE TITLE
standalone app. its only outputting 1 image instead of the video

### ISSUE THREAD

**Issue by mastergithub3574** [valadaptive/ntsc-rs#197]
its only outputting 1 image instead of the video. yah

**Comment by valadaptive** [comment]
I can't reproduce this. What video is it? Can you post a screen recording of the issue?

**Comment by mastergithub3574** [comment]
yes hello- its 2 multiple videos...and yeah sure i can..i can send the original files too..

https://github.com/user-attachments/assets/89d52341-e26e-4398-984f-b9dd13af3581

it doesnt even work when its rendered.. (this is just a example vid)

**Comment by valadaptive** [comment]
Ah, it seems like this is another issue with variable-framerate videos. I'll try to find a solution for that

**Comment by mastergithub3574** [comment]
ah ok. tyy :D

**Comment by emribilemir** [comment]
same for me!

**Comment by valadaptive** [comment]
Closing as a duplicate of #8

**Comment by mastergithub3574** [comment]
...

**Comment by valadaptive** [comment]
Not sure why GitHub says "not planned"--this will be fixed in the next version

**Comment by mastergithub3574** [comment]
was wondering that too..idek how this a duplicate..anyways ty xx
