### ISSUE TITLE
NTSC-rs worked for me once, but is not working anymore again.

### ISSUE THREAD

**Issue by noahpillor** [valadaptive/ntsc-rs#2]
I have tried to get it working but it was not working. I only have used it once and the 2nd time it was not launching at all.

I hate deleted my antivirus, and re-installed the files, and clicked "Run anyway" on the antivirus notice, it still does NOT WORK!!!

I have no other choice and it for some reason isn't working very well.

**Comment by valadaptive** [comment]
What do you mean "install"? There's no installer--you just unzip the .zip file. If you copy certain files but not others, or move files around relative to each other, it will likely break things.

If you go into the "bin" folder and run ntsc-rs-standalone.exe directly, does it work or at least show up in Task Manager after a while?

**Comment by noahpillor** [comment]
Oh. I had to use the term "install" as to download...

I think the way to get the launcher to work great is to unzip the .zip file?

**Comment by valadaptive** [comment]
Yes. As Windows says, applications in .zip files depend on other files to run properly, so you need to unzip the entire thing. Windows *should* show you a dialog box which tells you that:
![A411i](https://github.com/valadaptive/ntsc-rs/assets/79560998/fd160fc1-ce51-4fbf-a218-3134522146b8)

If you unzip the entire contents of the .zip file, does it run properly?

**Comment by valadaptive** [comment]
Going to assume you got it working--let me know if you still can't get it to open.
