### ISSUE TITLE
Ubuntu linux: How to open?

### ISSUE THREAD

**Issue by Degamisu** [valadaptive/ntsc-rs#20]
I downloaded the release standalone for Linux. However, I do not know how to run this. The console says after I run the command `./ntsc-rs-standalone`:

`bash: ./ntsc-rs-standalone: Permission denied`

Checked the Readme and I didn't find much information. I did run `sudo apt-get install qttools5-dev-tools`, but it didn't do anything. 

Thank you for any help!

**Comment by valadaptive** [comment]
You need to give it (and all executable files you download) execute permissions:
```bash
chmod +x ./ntsc-rs-standalone
```

**Comment by Degamisu** [comment]
Thanks! Yes I just found this repository and associated it with this. So I thought this was QT.
