### ISSUE TITLE
Scaling should automatically be enabled and default to 525 lines for NTSC video.

### ISSUE THREAD

**Issue by TheSystemGuy1337** [valadaptive/ntsc-rs#203]
Decently self explanatory. Since this is a NTSC simulator after all, scaling should automatically be enabled and the default value for said scaling should be 525 lines.

**Comment by oisintheblue** [comment]
why tho? isn't 480 already good enough? 


oh wait. i just looked it up, and it is 525 lines.

**Comment by Degamisu** [comment]
> why tho? isn't 480 already good enough?
> 
> oh wait. i just looked it up, and it is 525 lines. then what does have 480 lines then?

480 lines is the standard DV resolution, 525 is the standard analog NTSC resolution, and 360 is the standard Tape resolution.

**Comment by TheSystemGuy1337** [comment]
Found out that 480 lines for NTSC VHS is correct. I just looked it up. The default of 480 lines is correct for NTSC VHS videotape. But there should be a way for filters to set the amount of lines with certain presets (example the NTSCVHS flag would set 480 lines for NTSC videotape while NTSCANALOG would set 525 lines for television broadcasts).

If possible, we should add audio simulation too.

**Comment by LucianoTheWindowsFan** [comment]
AS for 525 lines, it refers to 525 scanlines in total. The visible scanlines are just 480 (although some sources say 486). Same thing for PAL and SECAM's 625 lines, in which only 576 of them are visible. The invisible lines are instead used for H-sync, closed captioning, teletext, etc.

**Comment by TheSystemGuy1337** [comment]
> AS for 525 lines, it refers to 525 scanlines in total. The visible scanlines are just 480 (although some sources say 486). Same thing for PAL and SECAM's 625 lines, in which only 576 of them are visible. The invisible lines are instead used for H-sync, closed captioning, teletext, etc.

In short, 480 scanlines is correct and was correct all along. Closing.
