### ISSUE TITLE
Feature suggestion:

### ISSUE THREAD

**Issue by Degamisu** [valadaptive/ntsc-rs#21]
A feature that I haven't seen in most of the _realistic_ VHS filters, is the ability to control `dot crawl` and `rainbow artifacts`.

Information on `dot crawl` and `rainbow artifacts` can be listed in this [Wikipidia article](https://en.wikipedia.org/wiki/Dot_crawl).

# Examples

![image](https://github.com/valadaptive/ntsc-rs/assets/149022474/b63d2bb8-bd43-4f6c-9d3f-eb549dca9f55)
**`Rainbow artifact` on the RAI test card.**
--
![image](https://github.com/valadaptive/ntsc-rs/assets/149022474/3101a1c3-f284-423a-930d-b02b3bd0e6a0)
**`Rainbow artifact` on the tennis racket.**
--
![image](https://github.com/valadaptive/ntsc-rs/assets/149022474/3248ce2d-5fb2-4be5-8993-9c6a7d13b713)
**`Dot crawl` on a composite video source`**
--
Thanks!

**Comment by valadaptive** [comment]
There are existing settings that allow some amount of control over dot control and rainbow artifacts:
- Setting "Input luma filter" to "None" increases rainbow artifacts. Setting it to "Box" decreases them.
- Setting "Chroma low-pass out" to "Light" or "None" increases rainbow artifacts.
- Setting "Chroma demodulation filter" to "Notch" increases dot crawl. 

The settings are definitely overwhelming and underexplained--at some point, I'm going to have to sit down and write a guide on what they do (and maybe rename them a bit--I named most of them the way ntscQT did).

Let me know what type of control over dot crawl/rainbow artifacts you want (do you want to make them more/less intense? Disable them entirely?)

**Comment by Degamisu** [comment]
i feel like the speed that they scroll (the rainbow artifacts) could be adjustable, so would the dot crawl be.

**Comment by Degamisu** [comment]
I think another thing that could be added is the rate that the dot crawl rolls. not sure if its implemented yet. unless this is physics based, I think it could be done.

one more thing. when you look at real VHS footage, you will see small distortions on like 1 frame. not sure what its called, but it would add to the realism significantly.

**Comment by valadaptive** [comment]
The speed of dot crawl and rainbow artifacts is based on framerate--the phase alternates every frame--so it's not possible to change its speed unfortunately.
