### ISSUE TITLE
Original video/image alignment

### ISSUE THREAD

**Issue by wdsongama** [valadaptive/ntsc-rs#217]
I'm trying to use the Premiere plugin to apply the effects to an image sequence, and my ultimate goal is to use the degraded images to train a super-resolution model. However, many effects misalign the input and output material. I tried setting the bandwith scale to the lowest value, which sort of resolves the aligment issue for some effects, but they took on a total different look, with some not even making any difference at any value no more. So I would be very grateful if you could make sure that no effect misaligns the image, even at the extreme values. If someone does want the image to be misaligned, I suggest a slider to bring the image to the right, left, top or bottom.

**Comment by valadaptive** [comment]
Actual analog video hardware (for both NTSC and VHS) delays the signal like this. If you want to align the encoded frames over the originals, you might need to add a post-processing step to line them up. Maybe by taking the difference between the encoded frame and the original, and shifting the encoded frame to the left until the difference reaches its minimum?
