### ISSUE TITLE
Just wondering abt smth.

### ISSUE THREAD

**Issue by oisintheblue** [valadaptive/ntsc-rs#228]
will there eventually be a discord server for ntsc-rs? that would be cool if there will be! 
if you do, you should probably set up some protection and moderation in the server before inviting anyone in so the server doesn't get raided or anything.

**Comment by thecatontheceiling** [comment]
I don't think there's a need for a "community server" for this project. There's a bunch of presets integrated already so a discord server which allows sharing presets wouldn't have much use either

**Comment by oisintheblue** [comment]
oh, k.

**Comment by valadaptive** [comment]
There still aren't any integrated presets, but there are a lot of good ones available in the Discussions here.

I'd prefer not to create a Discord, because it's not easily indexable unless you join. I prefer to keep useful information in public places.

**Comment by thecatontheceiling** [comment]
Guess I misinterpreted the latest release notes then
