### ISSUE TITLE
NTSC-RS standalone won't open

### ISSUE THREAD

**Issue by channel77** [valadaptive/ntsc-rs#233]
I recently downloaded the 0.9.0 standalone and ran it but it just wouldn't run, no error messages or anything. Any help would be greatly appreciated

**Comment by valadaptive** [comment]
You wouldn't happen to have Intel HD Graphics 3000 (I believe you can check in Device Manager under "display adapter") on Windows 10, would you?

**Comment by valadaptive** [comment]
Closing this issue as a month has gone by with no response. Let me know if you can provide more info
