### ISSUE TITLE
Error "Your GStreamer installation is missing a plug-in."

### ISSUE THREAD

**Issue by FunnyToonDerg** [valadaptive/ntsc-rs#243]
I keep getting this error pop up when I try to put some images to use, I don't understand why! I'm a Macbook user if it helps!

**Comment by valadaptive** [comment]
What images? Can you upload some of them here so that I can try to reproduce the issue?

**Comment by FunnyToonDerg** [comment]
![20241217181553_1](https://github.com/user-attachments/assets/a57caba6-2fbb-4a35-8e47-c352921b0254)
The image may not be the problem, but Incase it js, here ya go!

**Comment by valadaptive** [comment]
I can open this image just fine on my Intel Mac Mini. If you open "About This Mac" (in the top-left menu), what system specs do you have? I can't test on M1/M2/M3 hardware since it's quite expensive.

**Comment by FunnyToonDerg** [comment]
Unfortunately I have a MacBook Air with an M2 Chip 2022 release. ;(

**Comment by valadaptive** [comment]
OK, open the Terminal app (it should be under "Other" in Launchpad or "Utilities" in the Applications folder), and run the command:
```zsh
GST_DEBUG=4 /Applications/ntsc-rs.app/Contents/MacOS/ntsc-rs-standalone
```

After trying to load the .jpg and failing, close the application and post the full output of the terminal. You can use a [code block](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to format it properly.

**Comment by FunnyToonDerg** [comment]
`:3478:gst_element_finalize:<autoaudiosink0> 0x144194060 finalize
0:00:19.200013958 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3484:gst_element_finalize:<autoaudiosink0> 0x144194060 finalize parent
0:00:19.200016292 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3478:gst_element_finalize:<decodebin0> 0x1428f00c0 finalize
0:00:19.200017875 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3484:gst_element_finalize:<decodebin0> 0x1428f00c0 finalize parent
0:00:19.200020708 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3447:gst_element_dispose:<pipeline0> 0x14281c170 parent class dispose
0:00:19.200022417 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3478:gst_element_finalize:<pipeline0> 0x14281c170 finalize
0:00:19.200024042 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3484:gst_element_finalize:<pipeline0> 0x14281c170 finalize parent
0:00:19.200026708 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3400:gst_element_dispose:<eguisink0> 0x142894c00 dispose
0:00:19.200028708 18303    0x141e43190 INFO        GST_ELEMENT_PADS gstelement.c:876:gst_element_remove_pad:<eguisink0> removing pad 'sink'
0:00:19.200030958 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3447:gst_element_dispose:<eguisink0> 0x142894c00 parent class dispose
0:00:19.200034375 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3478:gst_element_finalize:<eguisink0> 0x142894c00 finalize
0:00:19.200036042 18303    0x141e43190 INFO         GST_REFCOUNTING gstelement.c:3484:gst_element_finalize:<eguisink0> 0x142894c00 finalize parent
funnytoonderg@TheFunnonThingy ~ %

**Comment by FunnyToonDerg** [comment]
Wait should I send the entire wall of text? Tryna figure out how to do this, my apologies!

**Comment by valadaptive** [comment]
You can probably upload it as a [Gist](https://gist.github.com/).

**Comment by FunnyToonDerg** [comment]
<script src="https://gist.github.com/FunnyToonDerg/9bd7b1c1cad116a0eeb912dd8ca8c304.js"></script>

**Comment by FunnyToonDerg** [comment]
https://gist.github.com/FunnyToonDerg/9bd7b1c1cad116a0eeb912dd8ca8c304#file-gistfile1-txt:~:text=Raw-,gistfile1.txt,-ns/ntsc%2Drs

There?

**Comment by valadaptive** [comment]
Looks like that image is a .webp file. GitHub converted it to a .jpeg when you uploaded it here, which is why I could load it.

GStreamer (what ntsc-rs uses to load images and videos) *should* be able to load .webp files, but I haven't tested it. Can you try re-downloading the image you posted above (now as a .jpeg) and opening it in ntsc-rs?

**Comment by FunnyToonDerg** [comment]
That works! Thank you, I didn't notice it was a .webp file!
