### ISSUE TITLE
The Render and Preview are buggy now

### ISSUE THREAD

**Issue by Legozilla** [valadaptive/ntsc-rs#32]
https://github.com/valadaptive/ntsc-rs/assets/157541946/602a3829-e0d4-4acf-bc8c-957992febb62

I have evidence of The Render and Preview being buggy in the current version.

**Comment by Degamisu** [comment]
what was the bug? Was it that `Internal Data Stream` error? if so, what is the filetype of the video/picture you are using?

**Comment by Legozilla** [comment]
I was using mp4 or Mov

**Comment by Degamisu** [comment]
> I was using a Mov

Then it might be the format itself. That, or it is some sort of image. `mov` is a Video format. The UI shows that it is just a single image (no scrubbing tab)

**Comment by valadaptive** [comment]
It's not a format issue; it's an issue where the current seek position of the video sometimes fails to update.

I apologize for not being more active on the issue tracker (I'm a full-time student so I have other responsibilities), but please resist the urge to play "backseat maintainer" and send people on wild goose chases.

**Comment by valadaptive** [comment]
Looks like it's a variable-framerate video which is being falsely detected as a still image. I don't know of a good way to tell them apart in GStreamer. I should probably ask.

I'm going to close this as a duplicate of https://github.com/valadaptive/ntsc-rs/issues/8.
