### ISSUE TITLE
(issue) dot crawl artifacts render at half speed?

### ISSUE THREAD

**Issue by nlolnlolnlolnlo** [valadaptive/ntsc-rs#33]
whenever i render out a sequence in ntsc-rs at 29.97 frames per second, the dot crawl seems to render at half of that and instead updates after two frames, slower than any other element. this causes some particularly nasty issues when rendering to 29.97i where it causes odd artifacts. is this intentional, and is there a way to fix it if not?

for some visual reference, here's a small comparison between real cvbs and ntsc-rs. i've looped two conseceutive frames from both sources. notice how the (exaggerated) composite noise moves between the two frames but the dot crawl doesn't on the ntsc-rs example?

real composite:
![ezgif-3-29546ca4ac](https://github.com/valadaptive/ntsc-rs/assets/154479340/9e40b365-36ba-4485-b56b-3cbaabb00754)
ntsc-rs:
![ezgif-3-56f41497e8](https://github.com/valadaptive/ntsc-rs/assets/154479340/5fc6bed7-01a3-4d57-be6a-5f0eea1ca7aa)

as always, feel free to reach out if you want my source files/clarification on anything.

**Comment by Degamisu** [comment]
Could I see your settings?

**Comment by nlolnlolnlolnlo** [comment]
[cvbs.json](https://github.com/valadaptive/ntsc-rs/files/14046175/cvbs.json)
![ntsc_rs_dotcrawl_testpattern](https://github.com/valadaptive/ntsc-rs/assets/154479340/3b756fb3-20c8-4cb3-b924-bc7b3954bed2)

**Comment by Degamisu** [comment]
Great, Thanks!

---

I tried out your settings and I also noticed your issue.

I ran the picture myself with my own settings and the result was successful. This helped measure the dotcrawl:composite noise rate.

![image](https://github.com/valadaptive/ntsc-rs/assets/149022474/6a480eca-3229-4dae-af89-c9b338260ea7)

For the settings, I used [DC.json](https://github.com/valadaptive/ntsc-rs/files/14050812/DC.json). Give these a try with the image and see if it fixes your problem.

https://github.com/valadaptive/ntsc-rs/assets/149022474/dae3e53d-30aa-4106-a655-8ab8a1c791a1

**Comment by nlolnlolnlolnlo** [comment]
this doesn't fix the problem - at least not for my usecase. the option "alternating" bobs the fields which messes up interlaced footage

**Comment by valadaptive** [comment]
This is still an issue with the "Use field" -> "Both" setting, but the new "Interleaved" setting should fix this.
