### ISSUE TITLE
Importing a Custom Video doesn't work

### ISSUE THREAD

**Issue by MasterNama17083** [valadaptive/ntsc-rs#34]
I loaded the video file it showed a blank background and then clicked on the play button but it didn't work.
![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/b5196c68-2d6f-4dc4-b647-dc40508b09ef)

**Comment by valadaptive** [comment]
Can you share the video file?

**Comment by MasterNama17083** [comment]
> Can you share the video file?
Unfortunately, I can't. we have random recording files that will not be public for this GitHub issue.

I'm trying to import my test video on the ntsc-rs program, but it is still not working:
![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/58ec5253-ef46-4044-b913-f4a4b2e99c24)


here's a good example video:
https://github.com/valadaptive/ntsc-rs/assets/80534869/519a50fa-96af-45b7-b677-a3965414395f

**Comment by valadaptive** [comment]
Just tried out the test video. Works fine for me:
![image](https://github.com/valadaptive/ntsc-rs/assets/79560998/800975a8-f054-4621-b365-30c311e14aec)

**Comment by valadaptive** [comment]
Is this still an issue? As I mentioned, the test video works for me. Does this happen with any video you load?

**Comment by MasterNama17083** [comment]
Hi @valadaptive I'm sorry for the 2 months ago late haven't responded.

I'm using with v0.5.2 _(the latest version)_. It's working any videos!
![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/e2055e00-38b5-4fa5-bf29-1095d9d45962)

**Comment by valadaptive** [comment]
Glad it's all working now!

**Comment by MasterNama17083** [comment]
## UPDATE:
Vegas Pro's exported videos should be work and any videos are won't work at all.
![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/cb731a3a-6cfd-4a59-b737-db9e67ea6ede)

**Comment by Degamisu** [comment]
> ## UPDATE:
> Vegas Pro's exported videos should be work and any videos are won't work at all. ![image](https://private-user-images.githubusercontent.com/80534869/333881636-cb731a3a-6cfd-4a59-b737-db9e67ea6ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk3MzgsIm5iZiI6MTcxNjcyOTQzOCwicGF0aCI6Ii84MDUzNDg2OS8zMzM4ODE2MzYtY2I3MzFhM2EtNmNmZC00YTU5LWI3MzctZGI5ZTY3ZWE2ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzMTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmJmZTg1NGQyYTU1ZjZiNWJmYzYwM2MyODc3M2YzYTJhOTM4MDU2NDg3NDc1ZTAwOWU5YWE5OTk0ODdmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwB_X8NI7_d3U9Qc1zwoKijEtahONoQT8ohES2-h4Lw)
> 
> I did a research.

i wonder if it has to do with spaces in the path?

**Comment by MasterNama17083** [comment]
> > ## UPDATE:
> > Vegas Pro's exported videos should be work and any videos are won't work at all. ![image](https://private-user-images.githubusercontent.com/80534869/333881636-cb731a3a-6cfd-4a59-b737-db9e67ea6ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk3MzgsIm5iZiI6MTcxNjcyOTQzOCwicGF0aCI6Ii84MDUzNDg2OS8zMzM4ODE2MzYtY2I3MzFhM2EtNmNmZC00YTU5LWI3MzctZGI5ZTY3ZWE2ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzMTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmJmZTg1NGQyYTU1ZjZiNWJmYzYwM2MyODc3M2YzYTJhOTM4MDU2NDg3NDc1ZTAwOWU5YWE5OTk0ODdmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwB_X8NI7_d3U9Qc1zwoKijEtahONoQT8ohES2-h4Lw)
> > I did a research.
> 
> i wonder if it has to do with spaces in the path?

no.

**Comment by Degamisu** [comment]
> > > ## UPDATE:
> > > Vegas Pro's exported videos should be work and any videos are won't work at all. ![image](https://private-user-images.githubusercontent.com/80534869/333881636-cb731a3a-6cfd-4a59-b737-db9e67ea6ede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk3MzgsIm5iZiI6MTcxNjcyOTQzOCwicGF0aCI6Ii84MDUzNDg2OS8zMzM4ODE2MzYtY2I3MzFhM2EtNmNmZC00YTU5LWI3MzctZGI5ZTY3ZWE2ZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEzMTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmJmZTg1NGQyYTU1ZjZiNWJmYzYwM2MyODc3M2YzYTJhOTM4MDU2NDg3NDc1ZTAwOWU5YWE5OTk0ODdmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwB_X8NI7_d3U9Qc1zwoKijEtahONoQT8ohES2-h4Lw)
> > > I did a research.
> > 
> > 
> > i wonder if it has to do with spaces in the path?
> 
> no.

what is the filetype? mp4?

**Comment by valadaptive** [comment]
Can you upload one of the videos that won't work?

**Comment by MasterNama17083** [comment]
> Can you upload one of the videos that won't work?

+ bandicam recorder codec works:  (original video, `MPEG-4` which is mp4 codec file)
![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/5ade0c8b-673a-47c1-adc3-3c7eb435d03a)
**Source:** https://github.com/valadaptive/ntsc-rs/assets/80534869/28a26865-52df-4b31-9267-ff2cc7eace82

+ MP4 Converter Online will not work:
![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/2692031f-6c1e-448e-9258-350934c603b8)
**Source _(you can try it what seems a problem to figure out)_:** https://github.com/valadaptive/ntsc-rs/assets/80534869/2a6e65aa-9d2f-40f2-b24e-1e900710cbd1

**Comment by MasterNama17083** [comment]
### Here's another one:
![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/39e491c6-ff08-4b2a-96cc-4d2ae0c2e7e4)
**Codec Contain:** Intel QSV = for intel CPU only. **WORKED!**
I did work using my animation test back in two months ago.

![image](https://github.com/valadaptive/ntsc-rs/assets/80534869/f582d79a-f1ed-43ea-8af3-b2ca5f7d01cb)
= **NOT WORK!**.

btw, I've used my old laptop since 2013 it has an AMD CPU.

**Comment by Degamisu** [comment]
hmm. the codec for the vegas pro is an AVC, and im pretty sure NTSC-RS only supports HEVEC? @valadaptive  is this true?

**Comment by valadaptive** [comment]
> hmm. the codec for the vegas pro is an AVC, and im pretty sure NTSC-RS only supports HEVEC? @valadaptive is this true?

No, that's incorrect. GStreamer should support both AVC (H.264) and HEVC (H.265). ntsc-rs had better support AVC, because it supports exporting it!

@MasterNama17083 I tried importing the one that you said didn't work, and it seems to load just fine on my machine:

![image](https://github.com/valadaptive/ntsc-rs/assets/79560998/13b4a42e-b95c-4ce4-8ccc-dab33fae2b49)

Can you re-download the one you uploaded from GitHub and try it again to make sure GitHub didn't do anything to the file upload?

If you still have access to your Intel laptop, try running ntsc-rs there and see if the file loads properly on that machine. ntsc-rs itself should work on all CPUs in the last 20 years, but some of the third-party video codecs *may* not.

**Comment by MasterNama17083** [comment]
> > hmm. the codec for the vegas pro is an AVC, and im pretty sure NTSC-RS only supports HEVEC? @valadaptive is this true?
> 
> No, that's incorrect. GStreamer should support both AVC (H.264) and HEVC (H.265). ntsc-rs had better support AVC, because it supports exporting it!
> 
> @MasterNama17083 I tried importing the one that you said didn't work, and it seems to load just fine on my machine:
> 
> ![image](https://github.com/valadaptive/ntsc-rs/assets/79560998/13b4a42e-b95c-4ce4-8ccc-dab33fae2b49)
> 
> Can you re-download the one you uploaded from GitHub and try it again to make sure GitHub didn't do anything to the file upload?
> 
> If you still have access to your Intel laptop, try running ntsc-rs there and see if the file loads properly on that machine. ntsc-rs itself should work on all CPUs in the last 20 years, but some of the third-party video codecs *may* not.

Alright, I'll try my another laptop and pc machine later to be work. Tomorrow.

**Comment by MasterNama17083** [comment]
@valadaptive I'm back. I've tried out these two devices:
## Another (Dell) Laptop - ✔️ worked:
 _[**CPU:** Intel Core i3 7020U | **GPU:** Intel HD Graphics 620]_
![test1](https://github.com/valadaptive/ntsc-rs/assets/80534869/cc07149b-80f2-4486-9303-c19c69da5554)
![test2](https://github.com/valadaptive/ntsc-rs/assets/80534869/eb657831-2863-4912-8446-48c53efdee39)
![test3](https://github.com/valadaptive/ntsc-rs/assets/80534869/ee7d643d-63b9-4153-8081-d5e3fa6c3319)

## PC Machine - ✔️ worked:
 _[**CPU:** Intel Core i5 4570 | **GPU:** Intel HD Graphics 4600]_
![test1](https://github.com/valadaptive/ntsc-rs/assets/80534869/2986f449-a863-45ba-90bf-10a22a2052c9)
![test2](https://github.com/valadaptive/ntsc-rs/assets/80534869/20895454-8a7f-4a6a-863f-b55f40a5d76d)
![test3](https://github.com/valadaptive/ntsc-rs/assets/80534869/8bac9352-1c7e-4f90-a931-03a834bed1a9)
### Download My Specifications (if you want): [Download Attach here](https://github.com/valadaptive/ntsc-rs/files/15487039/My.Devices.Specs.zip)

The only problem is I can't run everything all the videos for NTSC-RS on my old laptop which probably has an older GPU.
