### ISSUE TITLE
I think I broke nstc-es launcher. Which one is plug-in for OPENFX or something?

### ISSUE THREAD

**Issue by RedMations** [valadaptive/ntsc-rs#38]
Please help plz!

**Comment by RedMations** [comment]
This is impossible to open NSTC-RS launcher

**Comment by valadaptive** [comment]
What happens when you open it? Can you send a screen recording or screenshot?

You can find the OpenFX version on the [Releases page](https://github.com/valadaptive/ntsc-rs/releases/tag/v0.4.2).

**Comment by RedMations** [comment]
I already finded a OpenFx nstc-red folder zipped. But where do I put. Inside of nstc-rs application files or stay a folder?

**Comment by RedMations** [comment]
It’s just bundle?

**Comment by RedMations** [comment]
I clicked it, goes nothing to open. HELP!

**Comment by valadaptive** [comment]
1. Extract the OpenFX .zip (keeping the folder inside) to `C:\Program Files\Common Files\OFX\Plugins`).
2. Does running ntsc-rs-standalone in the `bin` folder work?

**Comment by valadaptive** [comment]
I'm going to close this issue since there's been no response in a week. Feel free to comment further if you're still experiencing issues
