### ISSUE TITLE
Website for ntsc-rs

### ISSUE THREAD

**Issue by valadaptive** [valadaptive/ntsc-rs#42]
It would be nice to have a proper website / landing page for ntsc-rs. Documentation could also be hosted there.

**Comment by nlolnlolnlolnlo** [comment]
i'd be 100% up to help with this!! i've messed with neocities and whatnot for a while. i'm admittedly not the most knowledgable when it comes to more advanced webdev stuff, but i have a fair bit of experience creating graphics/visual assets which could possibly be helpful

**Comment by Degamisu** [comment]
Github Pages hosts the site for free, however if you want something with no watermark and completely customizable, its gonna cost. Unless you have a server PC you can host it with!

**Comment by valadaptive** [comment]
Website is live at https://ntsc.rs/. Documentation is hosted there; the downloads and discussion pages link back here.
