### ISSUE TITLE
(suggestion) per-field artifacts

### ISSUE THREAD

**Issue by nlolnlolnlolnlo** [valadaptive/ntsc-rs#44]
a quirk of ntsc interlaced video that i've noticed when recreating and editing it is that each field is treated like a completely different frame, which is something that ntsc-rs can't really do at the moment. this affects almost all of the noise functions and even options like vertical chroma blend in vhs emulation. is this something that's fixable or in the works? i did see some commits related to interlacing function which makes me hopeful that this is something that could be solved.

![vlcsnap-2024-02-20-14h49m45s949](https://github.com/valadaptive/ntsc-rs/assets/154479340/806d7f3e-9fb5-484d-8022-4833190fc8d8)
real vhs example, notice how each field's noise is distinctly different? here's ntsc-rs to compare.
![ultimatetestvideo_ffv1-pcm_ntsc](https://github.com/valadaptive/ntsc-rs/assets/154479340/3a4f38df-0ea2-4f3d-b627-4459c98f2810)

**Comment by valadaptive** [comment]
I've added support for interleaved rendering in the 0.5.0 release. Try it out and let me know if it provides all the functionality you need.
