### ISSUE TITLE
Standalone client now hangs on open

### ISSUE THREAD

**Issue by CptKando** [valadaptive/ntsc-rs#45]
Previously operating without any issues for 1 week+. It now opens fullscreen window on my second monitor rather than primary or fullscreen maximised in the same location if I amend the settings in properties and will hang on open. Clicking the client will show a (Not Responding). No change in behaviour between normal or admin, open from extracted file or open from Zip. I have redownloaded the file and repeated the steps.

Only change to behaviour was on my previous render I fullscreened the video and closed it in that state.

**Comment by valadaptive** [comment]
By "fullscreen", do you mean that the window is maximized? I haven't implemented full-screen support.

Can you paste the contents of `%appdata%\ntsc-rs\app.ron` in a code block here?

**Comment by CptKando** [comment]
That's correct. It's opening by default at 2560x1440p

Sure thing:

`{
    "window": "(inner_position_pixels:Some((x:0.0,y:23.0)),outer_position_pixels:Some((x:-8.0,y:-8.0)),fullscreen:false,inner_size_points:Some((x:2560.0,y:1377.0)))",
    "egui": "(options:(zoom_factor:1.0,tessellation_options:(feathering:true,feathering_size_in_pixels:1.0,coarse_tessellation_culling:true,prerasterized_discs:true,round_text_to_pixels:true,debug_paint_clip_rects:false,debug_paint_text_rects:false,debug_ignore_clip_rects:false,bezier_tolerance:0.1,epsilon:0.00001),screen_reader:false,preload_font_glyphs:true,warn_on_id_clash:false),data:([(1708676004841398336,(type_id:(12000738070700777765),ron:\"(offset:(x:0.0,y:0.0),show_scroll:(x:false,y:false),content_is_too_large:(x:false,y:false),scroll_bar_interaction:(x:false,y:false),scroll_start_offset_from_top_left:(None,None),scroll_stuck_to_end:(x:true,y:false))\",generation:1)),(11726588273006219949,(type_id:(12000738070700777765),ron:\"(offset:(x:0.0,y:0.0),show_scroll:(x:false,y:false),content_is_too_large:(x:false,y:false),scroll_bar_interaction:(x:false,y:false),scroll_start_offset_from_top_left:(None,None),scroll_stuck_to_end:(x:true,y:true))\",generation:1)),(582828957119965208,(type_id:(12000738070700777765),ron:\"(offset:(x:0.0,y:0.0),show_scroll:(x:false,y:false),content_is_too_large:(x:false,y:false),scroll_bar_interaction:(x:false,y:false),scroll_start_offset_from_top_left:(None,None),scroll_stuck_to_end:(x:true,y:true))\",generation:1)),(8466011557389445029,(type_id:(12000738070700777765),ron:\"(offset:(x:0.0,y:0.0),show_scroll:(x:false,y:false),content_is_too_large:(x:false,y:false),scroll_bar_interaction:(x:false,y:false),scroll_start_offset_from_top_left:(None,None),scroll_stuck_to_end:(x:true,y:true))\",generation:3)),(1708781331375654114,(type_id:(12000738070700777765),ron:\"(offset:(x:0.0,y:0.0),show_scroll:(x:false,y:false),content_is_too_large:(x:false,y:false),scroll_bar_interaction:(x:false,y:false),scroll_start_offset_from_top_left:(None,None),scroll_stuck_to_end:(x:true,y:true))\",generation:7)),(1124551857816134977,(type_id:(536785424803254042),ron:\"(rect:(min:(x:425.0,y:25.0),max:(x:2560.0,y:49.0)))\",generation:1)),(6323965841510215554,(type_id:(536785424803254042),ron:\"(rect:(min:(x:0.0,y:1341.0),max:(x:425.0,y:1381.0)))\",generation:1)),(10269450108175403313,(type_id:(536785424803254042),ron:\"(rect:(min:(x:0.0,y:0.0),max:(x:2560.0,y:25.0)))\",generation:1)),(10222688696721015895,(type_id:(536785424803254042),ron:\"(rect:(min:(x:425.0,y:1341.0),max:(x:2560.0,y:1381.0)))\",generation:1)),(12766432230296682235,(type_id:(536785424803254042),ron:\"(rect:(min:(x:0.0,y:25.0),max:(x:425.0,y:1377.0)))\",generation:1)),(11337358779216517918,(type_id:(536785424803254042),ron:\"(rect:(min:(x:0.0,y:25.0),max:(x:425.0,y:49.0)))\",generation:1)),(7077682429583064773,(type_id:(6305895669885468581),ron:\"(cursor_range:Some((primary:(ccursor:(index:99,prefer_next_row:true),rcursor:(row:0,column:99),pcursor:(paragraph:0,offset:99,prefer_next_row:true)),secondary:(ccursor:(index:99,prefer_next_row:true),rcursor:(row:0,column:99),pcursor:(paragraph:0,offset:99,prefer_next_row:true)))),ccursor_range:None)\",generation:1))]),areas:{((0)):(areas:{(17078223717466474688):(pivot_pos:(x:6.0,y:100.0),pivot:((Min,Min)),size:(x:582.8475,y:40.0),interactable:false,edges_padded_for_resize:false),(1):(pivot_pos:(x:0.0,y:0.0),pivot:((Min,Min)),size:(x:2560.0,y:1377.0),interactable:true,edges_padded_for_resize:false),(2427002186613214914):(pivot_pos:(x:8.0,y:159.0),pivot:((Min,Min)),size:(x:237.0,y:72.0),interactable:true,edges_padded_for_resize:false),(2226677706662047613):(pivot_pos:(x:12.0,y:870.0),pivot:((Min,Min)),size:(x:308.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(5664305644897026815):(pivot_pos:(x:12.0,y:387.0),pivot:((Min,Min)),size:(x:500.0437,y:26.0),interactable:false,edges_padded_for_resize:false),(2892587504405114182):(pivot_pos:(x:6.0,y:142.0),pivot:((Min,Min)),size:(x:565.8475,y:40.0),interactable:false,edges_padded_for_resize:false),(12386485218200997576):(pivot_pos:(x:12.0,y:402.0),pivot:((Min,Min)),size:(x:359.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(1788747607183286984):(pivot_pos:(x:6.0,y:142.0),pivot:((Min,Min)),size:(x:360.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(13982607995853980680):(pivot_pos:(x:6.0,y:121.0),pivot:((Min,Min)),size:(x:451.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(5663280147381395595):(pivot_pos:(x:18.0,y:641.0),pivot:((Min,Min)),size:(x:261.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(13255320157579609420):(pivot_pos:(x:251.0,y:119.0),pivot:((Min,Min)),size:(x:451.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(10352217939855135052):(pivot_pos:(x:18.0,y:899.0),pivot:((Min,Min)),size:(x:189.07225,y:26.0),interactable:false,edges_padded_for_resize:false),(11320555628500919760):(pivot_pos:(x:12.0,y:227.0),pivot:((Min,Min)),size:(x:577.0437,y:26.0),interactable:false,edges_padded_for_resize:false),(17770059518223644432):(pivot_pos:(x:6.0,y:121.0),pivot:((Min,Min)),size:(x:576.8475,y:40.0),interactable:false,edges_padded_for_resize:false),(16624655502091984277):(pivot_pos:(x:257.0,y:555.0),pivot:((Min,Min)),size:(x:409.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(11625862450769257944):(pivot_pos:(x:14.0,y:803.0),pivot:((Min,Min)),size:(x:237.0,y:93.0),interactable:true,edges_padded_for_resize:false),(366151541030393753):(pivot_pos:(x:12.0,y:623.0),pivot:((Min,Min)),size:(x:364.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(12032326296421234972):(pivot_pos:(x:6.0,y:226.0),pivot:((Min,Min)),size:(x:255.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(18027602933520565853):(pivot_pos:(x:6.0,y:310.0),pivot:((Min,Min)),size:(x:494.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(8473640381469940062):(pivot_pos:(x:251.0,y:161.0),pivot:((Min,Min)),size:(x:284.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(3543343471255485727):(pivot_pos:(x:6.0,y:100.0),pivot:((Min,Min)),size:(x:257.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(5373012163233930204):(pivot_pos:(x:6.0,y:515.0),pivot:((Min,Min)),size:(x:377.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(13199351052390997917):(pivot_pos:(x:12.0,y:523.0),pivot:((Min,Min)),size:(x:285.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(10837069706658247139):(pivot_pos:(x:12.0,y:602.0),pivot:((Min,Min)),size:(x:299.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(6399780219189002404):(pivot_pos:(x:69.0,y:22.0),pivot:((Min,Min)),size:(x:162.0,y:51.0),interactable:true,edges_padded_for_resize:false),(7849780660030610084):(pivot_pos:(x:6.0,y:268.0),pivot:((Min,Min)),size:(x:413.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(6287893499664045413):(pivot_pos:(x:251.0,y:755.0),pivot:((Min,Min)),size:(x:480.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(15888483308761899943):(pivot_pos:(x:6.0,y:205.0),pivot:((Min,Min)),size:(x:182.07225,y:26.0),interactable:false,edges_padded_for_resize:false),(16200916000858311528):(pivot_pos:(x:12.0,y:381.0),pivot:((Min,Min)),size:(x:315.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(12098997269835684583):(pivot_pos:(x:12.0,y:481.0),pivot:((Min,Min)),size:(x:325.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(5264137408684750250):(pivot_pos:(x:12.0,y:581.0),pivot:((Min,Min)),size:(x:325.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(12844481029342072427):(pivot_pos:(x:6.0,y:163.0),pivot:((Min,Min)),size:(x:284.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(657259909146913706):(pivot_pos:(x:12.0,y:807.0),pivot:((Min,Min)),size:(x:409.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(13536990169391547752):(pivot_pos:(x:12.0,y:849.0),pivot:((Min,Min)),size:(x:401.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(5558166872614100715):(pivot_pos:(x:12.0,y:828.0),pivot:((Min,Min)),size:(x:404.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(14800936222663967152):(pivot_pos:(x:12.0,y:502.0),pivot:((Min,Min)),size:(x:277.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(15510687346474099953):(pivot_pos:(x:12.0,y:544.0),pivot:((Min,Min)),size:(x:179.07225,y:26.0),interactable:false,edges_padded_for_resize:false),(12326923429531071858):(pivot_pos:(x:12.0,y:460.0),pivot:((Min,Min)),size:(x:216.07225,y:26.0),interactable:false,edges_padded_for_resize:false),(7266967936224453939):(pivot_pos:(x:6.0,y:247.0),pivot:((Min,Min)),size:(x:525.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(4151930570126370932):(pivot_pos:(x:251.0,y:542.0),pivot:((Min,Min)),size:(x:230.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(12132482372226568562):(pivot_pos:(x:12.0,y:644.0),pivot:((Min,Min)),size:(x:142.07225,y:26.0),interactable:false,edges_padded_for_resize:false),(12468458143811213239):(pivot_pos:(x:259.0,y:563.0),pivot:((Min,Min)),size:(x:377.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(8109637623192136829):(pivot_pos:(x:12.0,y:208.0),pivot:((Min,Min)),size:(x:163.07225,y:26.0),interactable:false,edges_padded_for_resize:false),(4495370350962100413):(pivot_pos:(x:6.0,y:536.0),pivot:((Min,Min)),size:(x:256.07227,y:26.0),interactable:false,edges_padded_for_resize:false),(5789297428826178879):(pivot_pos:(x:12.0,y:360.0),pivot:((Min,Min)),size:(x:250.07227,y:26.0),interactable:false,edges_padded_for_resize:false)},order:[(order:Background,id:(1)),(order:Foreground,id:(2427002186613214914)),(order:Foreground,id:(11625862450769257944)),(order:Foreground,id:(6399780219189002404)),(order:Tooltip,id:(13255320157579609420)),(order:Tooltip,id:(12844481029342072427)),(order:Tooltip,id:(8109637623192136829)),(order:Tooltip,id:(8473640381469940062)),(order:Tooltip,id:(16200916000858311528)),(order:Tooltip,id:(12098997269835684583)),(order:Tooltip,id:(14800936222663967152)),(order:Tooltip,id:(13199351052390997917)),(order:Tooltip,id:(5789297428826178879)),(order:Tooltip,id:(5373012163233930204)),(order:Tooltip,id:(4495370350962100413)),(order:Tooltip,id:(5663280147381395595)),(order:Tooltip,id:(15510687346474099953)),(order:Tooltip,id:(12032326296421234972)),(order:Tooltip,id:(5264137408684750250)),(order:Tooltip,id:(12468458143811213239)),(order:Tooltip,id:(4151930570126370932)),(order:Tooltip,id:(16624655502091984277)),(order:Tooltip,id:(12386485218200997576)),(order:Tooltip,id:(7849780660030610084)),(order:Tooltip,id:(3543343471255485727)),(order:Tooltip,id:(7266967936224453939)),(order:Tooltip,id:(12132482372226568562)),(order:Tooltip,id:(11320555628500919760)),(order:Tooltip,id:(1788747607183286984)),(order:Tooltip,id:(15888483308761899943)),(order:Tooltip,id:(5664305644897026815)),(order:Tooltip,id:(10352217939855135052)),(order:Tooltip,id:(2226677706662047613)),(order:Tooltip,id:(13536990169391547752)),(order:Tooltip,id:(5558166872614100715)),(order:Tooltip,id:(17770059518223644432)),(order:Tooltip,id:(2892587504405114182)),(order:Tooltip,id:(13982607995853980680)),(order:Tooltip,id:(12326923429531071858)),(order:Tooltip,id:(10837069706658247139)),(order:Tooltip,id:(366151541030393753)),(order:Tooltip,id:(6287893499664045413)),(order:Tooltip,id:(18027602933520565853)),(order:Tooltip,id:(657259909146913706)),(order:Tooltip,id:(17078223717466474688))],visible_last_frame:[(order:Background,id:(1))],visible_current_frame:[],wants_to_be_on_top:[])})",
    "effect_settings": "{\"video_scanline_phase_shift\":2,\"tracking_noise_snow_anisotropy\":0.4699999988079071,\"tracking_noise\":true,\"ringing_frequency\":0.27000001072883606,\"vhs_edge_wave_speed\":0,\"input_luma_filter\":2,\"chroma_noise_intensity\":0,\"ringing\":true,\"head_switching\":true,\"bandwidth_scale\":1,\"tracking_noise_snow_intensity\":0.019999999552965164,\"chroma_delay_vertical\":0,\"use_field\":0,\"ringing_scale\":4.5,\"chroma_phase_noise_intensity\":0,\"head_switching_height\":8,\"chroma_lowpass_out\":2,\"snow_anisotropy\":0.5299999713897705,\"ringing_power\":1.5,\"tracking_noise_wave_intensity\":18,\"random_seed\":0,\"chroma_phase_error\":0,\"composite_noise_intensity\":0.0006000000284984708,\"chroma_delay_horizontal\":-20,\"composite_preemphasis\":0,\"chroma_demodulation\":0,\"vhs_chroma_vert_blend\":true,\"vhs_edge_wave_frequency\":0.05000000074505806,\"vhs_chroma_loss\":0,\"vhs_edge_wave_detail\":1,\"video_scanline_phase_shift_offset\":1,\"vhs_settings\":true,\"vhs_edge_wave\":0.800000011920929,\"vhs_tape_speed\":3,\"version\":1,\"tracking_noise_noise_intensity\":0.07000000029802322,\"head_switching_offset\":0,\"snow_intensity\":0,\"head_switching_horizontal_shift\":35,\"vhs_sharpen\":0.20000000298023224,\"chroma_lowpass_in\":1,\"tracking_noise_height\":13,\"vhs_edge_wave_enabled\":true}",
    "color_theme": "System",
}`

**Comment by CptKando** [comment]
That resolved it, we're good!
