### ISSUE TITLE
Interleave feature on OFX plugin messing up head switching and tracking noise 

### ISSUE THREAD

**Issue by Maris495** [valadaptive/ntsc-rs#47]
While I like the new interlace feature that was recently implemented, there's some sort of problem where if I pick an interleave field, there's double the head switching and tracking noise. Can there be a fix to this?
![interleave head switch error](https://github.com/valadaptive/ntsc-rs/assets/38088392/e7a0c3a9-c17b-472e-95d5-538bc8098422)

**Comment by valadaptive** [comment]
Is this in the UI or the OpenFX or AE plugin? I (embarrassingly) completely forgot to implement interleaved rendering in the plugins; I'll try to fix that in the next release.

**Comment by Maris495** [comment]
It is in the OpenFX plugin.

**Comment by valadaptive** [comment]
Fixed in the 0.5.1 release.

**Comment by Maris495** [comment]
thx!
