### ISSUE TITLE
Rendering causes NTSC-RS to crash

### ISSUE THREAD

**Issue by Legozilla** [valadaptive/ntsc-rs#48]
https://github.com/valadaptive/ntsc-rs/assets/157541946/90994cc6-df13-4091-8a22-98bd08242b23

For some reason, NTSC-RS crashed when I tried to render my videos.

**Comment by Oweblow1** [comment]
Hey, I've been having the same issue and they're blaming it on my OS and hardware.

**Comment by valadaptive** [comment]
> Hey, I've been having the same issue and they're blaming it on my OS and hardware even though it's not the issue.

The application itself crashing is not the same as *your entire OS* crashing. Please stop spamming other issues that are different from the problem you're experiencing.

**Comment by Oweblow1** [comment]
I'm sorry.
