### ISSUE TITLE
Preset manager

### ISSUE THREAD

**Issue by valadaptive** [valadaptive/ntsc-rs#50]
It would be nice for the standalone app to have a way to more efficiently save and load presets than saving and loading files. Something like a list of presets at the bottom of the effect settings, backed by a folder in whichever app data directory ntsc-rs uses, would be useful.

**Comment by oisintheblue** [comment]
would the presets still be JSON filetype? i'd like to still be able to share presets

**Comment by valadaptive** [comment]
Yes; I have no plans to move away from JSON.

**Comment by valadaptive** [comment]
Released in v0.8.0.

**Comment by Degamisu** [comment]
Small question about this. I have a specific folder I keep my presets and I was wondering if it's possible to switch folders in the future?
