### ISSUE TITLE
Latest release (0.5.1) crashes on After Effects 2023

### ISSUE THREAD

**Issue by DrFalamin** [valadaptive/ntsc-rs#51]
Hello, I tried to install the new version of this plugin (which I love btw) on After Effects 2023 but when I apply him on an adjustment layer, the program crashes instantly. I tried with the previous version and it works without any problem at all...

**Comment by valadaptive** [comment]
Fixed in 0.5.2

**Comment by Mews** [comment]
I am still running into this on version 0.8.0

**Comment by valadaptive** [comment]
@Mews Sorry for being a month late. Would you mind opening a new issue and describing your problem in more detail?

**Comment by Mews** [comment]
Hi I don't know what changed but after a day or two of fighting it it just stopped happening entirely.
I'll open a new issue if it starts happening again but for now it's working well 👍
