### ISSUE TITLE
It isn't working on my first run!

### ISSUE THREAD

**Issue by smfthe1199** [valadaptive/ntsc-rs#6]
Tried restarting but didn't work!

**Comment by valadaptive** [comment]
Some people seem to have issues using the launcher. After extracting all the files from the .zip, go into the "bin" folder and run ntsc-rs-standalone--does that work?

**Comment by smfthe1199** [comment]
not either, thus I haven't installed Python yet!

**Comment by valadaptive** [comment]
ntsc-rs doesn't use Python; you don't need to have it installed.

Have you extracted the files from the .zip or are you clicking on the .zip to open it and trying to run it from there? You need to extract the files or it won't run.

**Comment by smfthe1199** [comment]
I have extracted the files! I opened it up, nothing!

**Comment by smfthe1199** [comment]
I might gonna restart this device again and re-extract it to see how it goes! (I deleted the extracted file, still the .zip file remains)!, I will issue an update to see how it goes!

**Comment by smfthe1199** [comment]
UPDATE: It's still not working!

**Comment by valadaptive** [comment]
What version of Windows are you running, and can you provide a screen recording or at least screenshots of how you're trying to open the application?

**Comment by smfthe1199** [comment]
I'm Using Windows 10 (22H2)

**Comment by smfthe1199** [comment]
Uploading My Video.mp4…

**Comment by smfthe1199** [comment]
Nah I already got a screen recorder!

**Comment by smfthe1199** [comment]
Uploading My Video.mp4…

**Comment by smfthe1199** [comment]
Perhaps a link to my Google Drive that shows you how I open up Ntsc-rs: https://drive.google.com/file/d/1HVe3XTpAa1TVRf_VNjsQJv4meVwS5j_V/view?usp=drive_link

**Comment by valadaptive** [comment]
Check your sharing settings--I can't access it

**Comment by smfthe1199** [comment]
Perhaps you can download it, preview it, and then delete it afterwards!

**Comment by valadaptive** [comment]
Can you try another recording of opening ntsc-rs-standalone.exe in the bin folder? You should be able to upload it directly to GitHub.

**Comment by smfthe1199** [comment]
It will say "Uploading [filename].mp4" with no indication!, So I'll do a shorter recording with the same thing but in bin file!

**Comment by valadaptive** [comment]
You just need to wait a while (it might take a long time depending on your internet speed) but it'll be replaced with the URL of the uploaded file after you wait long enough.

**Comment by smfthe1199** [comment]
https://drive.google.com/file/d/1s6ikKIdBbmQ84iwrZnuS3bnYChQp7ens/view?usp=sharing

**Comment by valadaptive** [comment]
Hm, not sure what's going on yet. I confirmed that the latest version runs on my machine, also Windows 10 22H2. I can help debug more tomorrow.

**Comment by smfthe1199** [comment]
JTLYK, I have installed Chocolatey and installed FFMPEG 3.0, I then tried to get the procedure from the installing of NTSCQT (which is what I have) and it turned out the CMD-let of "git" isn't available in either CMD, PowerShell (with Administrator privileges), and Terminal Runing Windows PowerShell (with Administrator privileges), nothing worked, I will still try, uninstall programs of mine, even trying it on another computer! (What I'm using right now is the main pc). If it worked then you may close the case!

**Comment by smfthe1199** [comment]
Does this need anything or something?

**Comment by valadaptive** [comment]
Everything it needs should be bundled with the .zip file.

Download [this debug version of ntsc-rs-standalone](https://drive.google.com/file/d/1g4u37VzWW8qCI-oOh2N8wGze44pgbSpd/view?usp=sharing), and extract it.

Then, run the following commands in Command Prompt:
```
cd /d "C:/path/to/ntsc-rs-standalone-windows/bin"
SET RUST_BACKTRACE=full
ntsc-rs-standalone.exe
```
(but replace "C:/path/to/ntsc-rs-standalone-windows/bin" with the *full* path to the `bin` folder wherever you extracted the debug build to).

If you've done everything correctly, you should get an error message. If you get `'ntsc-rs-standalone.exe' is not recognized as an internal or external command, operable program or batch file.`, that means you're in the wrong folder, but otherwise, paste the error message here.

**Comment by smfthe1199** [comment]
tysm! I should do that tomorrow!

**Comment by smfthe1199** [comment]
Get this to google drive, (unless if I am able to access this, I'll delete this comment)

**Comment by smfthe1199** [comment]
Hold on!

**Comment by smfthe1199** [comment]
I might do that at anytime!

**Comment by smfthe1199** [comment]
Transfer this to Google Drive, I couldn't access it!

**Comment by smfthe1199** [comment]
"[2023-12-13T06:30:18Z ERROR eframe::native::run::glow_integration] failed to set swap interval due to error: Error { raw_code: None, raw_os_message: None, kind: NotSupported("swap contol extrensions are not supported") }
thread 'main' panicked at 'An OpenGL error occurred: egui_glow requires opengl 2.0+.
', C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:756:43
stack backtrace:
   0:     0x7ff62e75942c - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff62e77a86b - core::fmt::rt::Argument::fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\rt.rs:138
   2:     0x7ff62e77a86b - core::fmt::write
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\fmt\mod.rs:1094
   3:     0x7ff62e754d2f - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\io\mod.rs:1714
   4:     0x7ff62e7591db - std::sys_common::backtrace::_print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff62e7591db - std::sys_common::backtrace::print
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff62e75bcaa - std::panicking::default_hook::closure$1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:269
   7:     0x7ff62e75b8ff - std::panicking::default_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:288
   8:     0x7ff62e75c35e - std::panicking::rust_panic_with_hook
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:705
   9:     0x7ff62e75c24d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:597
  10:     0x7ff62e75a079 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\sys_common\backtrace.rs:151
  11:     0x7ff62e75bf50 - std::panicking::begin_panic_handler
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
  12:     0x7ff62e785525 - core::panicking::panic_fmt
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
  13:     0x7ff62deebfea - eframe::native::run::glow_integration::impl$1::init_run_state::closure$0
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:756
  14:     0x7ff62de6fb54 - enum2$<core::result::Result<egui_glow::painter::Painter,alloc::string::String> >::unwrap_or_else<egui_glow::painter::Painter,alloc::string::String,eframe::native::run::glow_integration::impl$1::init_run_state::closure_env$0>
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\result.rs:1428
  15:     0x7ff62deeb423 - eframe::native::run::glow_integration::GlowWinitApp::init_run_state
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:755
  16:     0x7ff62deed1fd - eframe::native::run::glow_integration::impl$2::on_event
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:991
  17:     0x7ff62decdd81 - eframe::native::run::run_and_return::closure$0<eframe::native::run::glow_integration::GlowWinitApp>
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:198
  18:     0x7ff62de98407 - winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<enum2$<eframe::native::run::UserEvent>,eframe::native::run::run_and_return::closure_env$0<eframe::native::run::glow_integration::GlowWinitApp> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop.rs:260
  19:     0x7ff62de45c05 - alloc::boxed::impl$48::call_mut<tuple$<enum2$<winit::event::Event<enum2$<eframe::native::run::UserEvent> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<enum2$<eframe::native::run::
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\alloc\src\boxed.rs:2000
  20:     0x7ff62de64e47 - winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum2$<eframe::native::run::UserEvent> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop\runner.rs:250
  21:     0x7ff62de3d044 - core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\panic\unwind_safe.rs:271
  22:     0x7ff62df070ec - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,tuple$<> >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:500
  23:     0x7ff62df09c63 - flate2::zio::impl$6::drop<ref_mut$<ref_mut$<std::io::cursor::Cursor<ref_mut$<alloc::vec::Vec<u8,alloc::alloc::Global> > > > >,flate2::mem::Compress>
  24:     0x7ff62df06c1a - std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > > >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panicking.rs:464
  25:     0x7ff62de4bd09 - std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,tuple$<> >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\panic.rs:142
  26:     0x7ff62de636b0 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::catch_unwind<enum2$<eframe::native::run::UserEvent>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::clos
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop\runner.rs:157
  27:     0x7ff62de64bdb - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::call_event_handler<enum2$<eframe::native::run::UserEvent> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop\runner.rs:242
  28:     0x7ff62de646e5 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::call_new_events<enum2$<eframe::native::run::UserEvent> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop\runner.rs:402
  29:     0x7ff62de63b63 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::move_state_to<enum2$<eframe::native::run::UserEvent> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop\runner.rs:312
  30:     0x7ff62de65497 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::poll<enum2$<eframe::native::run::UserEvent> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop\runner.rs:206
  31:     0x7ff62de97ad9 - winit::platform_impl::platform::event_loop::EventLoop<enum2$<eframe::native::run::UserEvent> >::run_return<enum2$<eframe::native::run::UserEvent>,eframe::native::run::run_and_return::closure_env$0<eframe::native::run::glow_integration::GlowWinitApp> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform_impl\windows\event_loop.rs:269
  32:     0x7ff62deda63e - winit::platform::run_return::impl$0::run_return<enum2$<eframe::native::run::UserEvent>,eframe::native::run::run_and_return::closure_env$0<eframe::native::run::glow_integration::GlowWinitApp> >
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.6\src\platform\run_return.rs:51
  33:     0x7ff62decdadc - eframe::native::run::run_and_return<eframe::native::run::glow_integration::GlowWinitApp>
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:147
  34:     0x7ff62deed62f - eframe::native::run::glow_integration::run_glow::closure$0
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:1105
  35:     0x7ff62decd8b0 - eframe::native::run::with_event_loop::closure$0<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > >,eframe::native::run::glow_integration::run_glow::closure_env$0>
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:130
  36:     0x7ff62dea9025 - std::thread::local::LocalKey<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::native::run::UserEvent> > > > > >::try_with<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\thread\local.rs:270
  37:     0x7ff62dea88f3 - std::thread::local::LocalKey<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::native::run::UserEvent> > > > > >::with<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::na
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\thread\local.rs:246
  38:     0x7ff62decd768 - eframe::native::run::with_event_loop<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > >,eframe::native::run::glow_integration::run_glow::closure_env$0>
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:124
  39:     0x7ff62deed427 - eframe::native::run::glow_integration::run_glow
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\native\run.rs:1102
  40:     0x7ff62de58333 - eframe::run_native
                               at C:\Users\adroitwhiz\.cargo\registry\src\index.crates.io-6f17d22bba15001f\eframe-0.23.0\src\lib.rs:227
  41:     0x7ff62d414292 - ntsc_rs_standalone::main
                               at C:\Users\adroitwhiz\Documents\ntsc-rs\crates\gui\src\bin\ntsc-rs-standalone.rs:117
  42:     0x7ff62d4354ab - core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > (*)(),tuple$<> >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
  43:     0x7ff62d43c2fe - std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > (*)(),enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc:
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\sys_common\backtrace.rs:135
  44:     0x7ff62d43cbb1 - std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\rt.rs:166
  45:     0x7ff62e74e6b8 - std::rt::lang_start_internal::closure$2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\rt.rs:148
  46:     0x7ff62e74e6b8 - std::panicking::try::do_call
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:500
  47:     0x7ff62e74e6b8 - std::panicking::try
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:464
  48:     0x7ff62e74e6b8 - std::panic::catch_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panic.rs:142
  49:     0x7ff62e74e6b8 - std::rt::lang_start_internal
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\rt.rs:148
  50:     0x7ff62d43cb8a - std::rt::lang_start<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > > >
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\std\src\rt.rs:165
  51:     0x7ff62d41ae09 - main
  52:     0x7ff62e783464 - invoke_main
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  53:     0x7ff62e783464 - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  54:     0x7ffeefb27344 - BaseThreadInitThunk
  55:     0x7ffef04626b1 - RtlUserThreadStart"

**Comment by valadaptive** [comment]
It looks like there's an issue with your graphics card. Do you have any trouble running things like 3D games?

If you go to the Windows "Display" settings, scroll down to the bottom and click "Advanced display settings", then click "Display adapter properties for Display 1", it should open a window telling you what graphics card you have. Can you send a screenshot?

**Comment by smfthe1199** [comment]
I'll do so later.

**Comment by smfthe1199** [comment]
![Screenshot 2023-12-14 114145](https://github.com/valadaptive/ntsc-rs/assets/153495179/90b7d62e-cdc4-4548-866b-ebef92bb757e)

**Comment by valadaptive** [comment]
It seems like your graphics card is too old to support 3D acceleration, at least on Windows 10. Unfortunately, that's necessary to run ntsc-rs.

I haven't tested it myself and have no idea if it will work, but you may be able to try [the mesa-dist-win graphics driver](https://github.com/pal1000/mesa-dist-win/releases/tag/23.3.0) (probably `mesa3d-23.3.0-release-msvc.7z`). It includes a software implementation of 3D rendering.

**Comment by smfthe1199** [comment]
Allrighty then!

**Comment by smfthe1199** [comment]
MESA: error: ZINK: failed to load vulkan-1.dll

**Comment by valadaptive** [comment]
Maybe it's using the wrong driver? Try this in Command Prompt:
```
cd /d "C:/path/to/ntsc-rs-standalone-windows/bin"
SET GALLIUM_DRIVER=llvmpipe
ntsc-rs-standalone.exe
```

**Comment by smfthe1199** [comment]
not working still!

**Comment by valadaptive** [comment]
Any error message this time?

**Comment by smfthe1199** [comment]
Doesn't display anything and doesn't yet do anything!

**Comment by smfthe1199** [comment]
Sorry valdaptive but I have to close the case here, since my PC here don't support that! Thanks for your corporation!
