### ISSUE TITLE
Virtual machines error

### ISSUE THREAD

**Issue by RedMations** [valadaptive/ntsc-rs#62]
I’m having a problem to launch NTSC-RS Effect by using parallels desktop on Mac.

**Comment by RedMations** [comment]
When I hit click on ntsc-Rs launcher on windows 10 virtual machine, there’s an error pop up says: “the code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem.” Hopefully it HELPS! Thanks

**Comment by Degamisu** [comment]
Hi! `VCRUNTIME140.dll` is an executable that contains vital code to execute C and C++ code. If you want the Visual C++ runtime, I provided a download link [here.](https://aka.ms/vs/17/release/vc_redist.x86.exe) Run and install VCR140 and you should be able to run NTSC-RS

**Comment by RedMations** [comment]
Well I hope so.

**Comment by Degamisu** [comment]
let me know how it goes!

**Comment by RedMations** [comment]
OH No! VCRUNTIME140.dll is still not found while I already installed Microsoft visual C++. Well I guess I’m sad now. :(

**Comment by RedMations** [comment]
What did I SERIOUSLY broke…? 😢

**Comment by RedMations** [comment]
Oh! I forgot I was looking for YouTube tutorials I watch

**Comment by RedMations** [comment]
Nevermind It Works while I pasting DLL file inside the ds-dk folder on system32 folder inside

**Comment by valadaptive** [comment]
Glad to hear it works now!

**Comment by RedMations** [comment]
Now it’s working! Thanks!

**Comment by Degamisu** [comment]
Glad to hear its working! 🎊
