### ISSUE TITLE
Keyframes

### ISSUE THREAD

**Issue by arwenrei** [valadaptive/ntsc-rs#67]
Keyframes are things you can add to the video timeline. for example, say keyframe 01 has 0 chroma loss, and keyframe 02 has 12% chroma loss. As the video player gets closer to keyframe 02, the chroma loss increases. The farther it is, the longer it takes for that process to continue.

**Comment by valadaptive** [comment]
The standalone ntsc-rs application is not meant to be a replacement for video editing software, and implementing things like keyframing would add a huge amount of complexity to it. If you want to use such features, you should probably just get DaVinci Resolve or Hitfilm, both of which are free IIRC.
