### ISSUE TITLE
[Suggestion] Support for interlaced video input and output

### ISSUE THREAD

**Issue by rgm89git** [valadaptive/ntsc-rs#7]
There are some input material, like testing and stuff, that it's only available in interlaced.

**ntsc-rs** only has support for progressive material, as some demodulation filters average the two lines, as in Both, the whole frame is processed, instead of fields.

_(Order: Field mode, demodulation filter)_
Both, Notch:
![image](https://github.com/valadaptive/ntsc-rs/assets/40833244/32d1b769-a308-402e-99a6-f1a182317d56)

Both, 2-line comb:
![image](https://github.com/valadaptive/ntsc-rs/assets/40833244/ac6d5c77-8f13-4fc8-9f3d-b6e55e5b7837)

I did noticed there's a Upper and Lower field modes, that can do the separation for the two fields.
Removing these, we only have Alternating, which it's the same with Upper and Lower, but alternating between the twos. This mode is for progressive sources.

So, for interlaced input, we can use both field modes, and interleave them.
Both ntscQT and ntscQT+ have an interleaved interlaced mode.

**Comment by rgm89git** [comment]
Hi!
I'm just wanting to remind you of this issue.

**Comment by nlolnlolnlolnlo** [comment]
a workaround that i've used is to use ffmpeg to interlace afterwards with a simple script like this:

`ffmpeg -i "in.avi" -vf interlace=scan=tff -sws_flags neighbor -c:v ffv1 "out.mkv"`

there are some small issues with how framerates are handled which can sorta complicate things (see my issue at https://github.com/valadaptive/ntsc-rs/issues/33) but overall it's seamless enough.

**Comment by rgm89git** [comment]
> a workaround that i've used is to use ffmpeg to interlace afterwards with a simple script like this:
> 
> `ffmpeg -i "in.avi" -vf interlace=scan=tff -sws_flags neighbor -c:v ffv1 "out.mkv"`
> 
> there are some small issues with how framerates are handled which can sorta complicate things (see my issue at #33) but overall it's seamless enough.

Good, but... before using ntsc-rs, how i can transform an interlaced video to a way for ntsc-rs to use and not destroy the interlacing *(still in ffmpeg)*?

**Comment by valadaptive** [comment]
I've added support for interleaved rendering in the 0.5.0 release. Try it out and let me know if it provides all the functionality you need.

**Comment by valadaptive** [comment]
Closing this issue since 0.5.0 added support for interlacing; prefer opening new issues for future interlacing-related functionality.

**Comment by rgm89git** [comment]
Thanks a lot! 💜 👍
