### ISSUE TITLE
Option to scale the width and height separately

### ISSUE THREAD

**Issue by oisintheblue** [valadaptive/ntsc-rs#72]
it would be cool to be able to make every video or image imported be 4:3 or 16:9.
and have a mode for it where you can either stretch or crop the video.

**Comment by valadaptive** [comment]
The ntsc-rs standalone GUI is not meant to replace editing software, and I don't want to add things that existing software is already capable of doing. Cropping and stretching videos is a feature general enough that I think it's better suited for video editing software (like Resolve, Hitfilm, or Natron, which are free and can use ntsc-rs as a plugin). Keyframing has also been suggested before, which I believe falls under a similar category.

I'm aware that free video editing software is very hard to come by, and much of it doesn't support OpenFX, but I don't want ntsc-rs to turn into a half-baked reimplementation of a nonlinear editor. I do have very long-term aspirations to create actual video editing software, but that's a long way off from this project.
