### ISSUE TITLE
(issue possibly??) sharpening options are overly excessive

### ISSUE THREAD

**Issue by nlolnlolnlolnlo** [valadaptive/ntsc-rs#73]
![sharpening](https://github.com/valadaptive/ntsc-rs/assets/154479340/83360334-24f5-4d98-964c-1ff937e781fe)
this is a problem that i noticed in ntscqt as well, is there a way to tweak the ntsc-rs sharpening to more closely match a real vcr's sharpening? it seems like it extends out a few more pixels than it should

**Comment by valadaptive** [comment]
The sharpening "size" is tied to the VHS tape speed setting--what do you currently have it at? If it's set to SP and still excessively wide, I can try to add finer control.

**Comment by oisintheblue** [comment]
a more noticeable difference between the real vhs images and the ntsc-rs images is how big the grayscale gradient thingy is

**Comment by oisintheblue** [comment]
prob because of the bandwidth scale maybe

**Comment by valadaptive** [comment]
If you're referring to the subtle rainbow fringe, I think that's the "Input luma filter" setting's doing. It reduces crosstalk between chroma and luma when enabled.

**Comment by oisintheblue** [comment]
no, im referring to the grayscale gradient thingy on the left side of the photo

**Comment by oisintheblue** [comment]
it looks a little big

**Comment by Degamisu** [comment]
> no, im referring to the grayscale gradient thingy on the left side of the photo

Color bleeding. It happens when the overscan of the image is casted onto the VHS signal, and that gets smeared. I'm not 100% sure on how it works, but that's from my experience

**Comment by nlolnlolnlolnlo** [comment]
i'm not sure how helpful it is but i did some blend mode stuff and was able to approximate the vcr's maximum sharpening as an overlay

unsharpened image and extracted sharpening
![vhs_sp-soft](https://github.com/valadaptive/ntsc-rs/assets/154479340/b6b264a2-0a21-479e-8742-cf1e9c1bbed8)
![sharpness](https://github.com/valadaptive/ntsc-rs/assets/154479340/942648f5-767c-4fa7-8442-9c518b97f8ad)

**Comment by oisintheblue** [comment]
seems like theres more horizitional sharpness going on than vertical sharpness. what if the sharpness option was split in horizitional and vertical?

**Comment by nlolnlolnlolnlo** [comment]
vertical sharpening is not something that would work with interlacing

**Comment by oisintheblue** [comment]
then dont split the option in half but instead make the vertical sharpening less than the horizitional sharpening

**Comment by oisintheblue** [comment]
while the sharpness option still being one thing

**Comment by valadaptive** [comment]
AFAIK vertical sharpening isn't a thing in VHS because all the blurring happens horizontally, that is, per scanline. I will thus not be adding vertical sharpening, and I don't think it's what @nlolnlolnlolnlo was asking for in the first place.

**Comment by valadaptive** [comment]
Quick update on this: I *think* the current bandpass filter (three cascaded constant-k filters, inherited all the way back from composite-video-simulator) is to blame. I added a slider to control the cutoff for the sharpening highpass filter, but it does almost nothing.

At some point, I'll try to add the option to use a Butterworth filter or similar instead. Hopefully that'll also increase accuracy for everything else that uses a bandpass filter.

**Comment by valadaptive** [comment]
I've implemented the option to use a Butterworth filter as the low-pass filter throughout, and also made the VHS sharpening filter's frequency adjustable (since it actually does something with the Butterworth filter). I've managed to get this result:
[butter.json](https://github.com/valadaptive/ntsc-rs/files/15040665/butter.json)

![316611529-b56548ea-dae8-4391-bbd9-b7e6043ea559_ntsc](https://github.com/valadaptive/ntsc-rs/assets/79560998/cc66081a-b7b5-47b0-a24b-46299f685f00)

Let me know if this suits your needs.

**Comment by nlolnlolnlolnlo** [comment]
i completely forgot to reply but that's perfect. closing the issue now
