### ISSUE TITLE
v0.5.7 Standalone Render Broken (?)

### ISSUE THREAD

**Issue by ronedgecomb** [valadaptive/ntsc-rs#76]
When using the Windows Standalone desktop application for v0.5.7, I noticed an issue where it appears that only half of the frame / image is being rendered, while the other half is completely black. Tried reproducing the issue with v0.5.6, but it seems like it's only an issue in the most recent release. I double checked and made sure that I had the correct Microsoft Visual C++ Redistributable installed, so I'm certain that's not it.

Unmodified Image:
![image-unmodified](https://github.com/valadaptive/ntsc-rs/assets/138141729/d76834c9-1aeb-42e3-9762-4da8adf05efa)

NTSC-RS v0.5.7:
![image-ntsc_v0 5 7](https://github.com/valadaptive/ntsc-rs/assets/138141729/5a36b072-90b7-4b4a-93cc-7065cfb214c7)

NTSC-RS v0.5.6:
![image-ntsc_v0 5 6](https://github.com/valadaptive/ntsc-rs/assets/138141729/a472f9f4-0246-462e-91b7-0c33dd97e9f2)

**Comment by valadaptive** [comment]
Thanks for the report! I've fixed this in v0.5.8.
