### ISSUE TITLE
Internal Data Stream Error

### ISSUE THREAD

**Issue by CoolAnimateCanGacha** [valadaptive/ntsc-rs#8]
Hey there.
Whenever I input the fps and duration, the file disappears and displayed "Internal Data Stream Error".
How to fix this one?
![Uploading Scree![Screenshot (395)](https://github.com/valadaptive/ntsc-rs/assets/70521721/8b2f0c26-c915-4edb-ad4e-f630fed79262)
![Screenshot (396)](https://github.com/valadaptive/ntsc-rs/assets/70521721/025deca6-400e-4a67-b188-96fb4e1a232f)

**Comment by valadaptive** [comment]
You shouldn't be able to set the FPS on a video file--the FPS and duration controls should only be editable on still images. Can you upload the .mp4 you're trying to use?

**Comment by CoolAnimateCanGacha** [comment]
Tried exporting but the output is audio only
The file format is mp4. How to fix it?

Here's proof: 

https://github.com/valadaptive/ntsc-rs/assets/70521721/d07905f7-583d-44f8-9c85-63d7a1710582

**Comment by valadaptive** [comment]
No, I mean can you upload the *input* .mp4 file?

**Comment by CoolAnimateCanGacha** [comment]
The file is too large so...
https://drive.google.com/file/d/1CpdceE6VZ1apRoZq_DDod6ZIpn7hGfZB/view?usp=sharing

**Comment by valadaptive** [comment]
Seems like it's a variable-framerate video. It'll take a bit of work to fix this issue; in the meantime, if you have any video editing software, try importing the video and re-rendering it with a fixed framerate.

**Comment by valadaptive** [comment]
This has been (finally) fixed in v0.9.0.
