### ISSUE TITLE
command line version for bash script [suggestion | enhancement ]

### ISSUE THREAD

**Issue by abcnorio** [valadaptive/ntsc-rs#80]
Is it possible to add a commandline version instead of using the GUI?

advantages:

- batch processing, esp. for many images/ videos with constant or changing parameters (read from config file)
- embedding into scripts (bash, whatever, ...)

? Thx!

**Comment by UltraBlackLinux** [comment]
I'm really fond of this idea as well. I well and truly love analog distortion and would almost like to slap it on any wallpaper i have. Just for that I'd love to have this generate new distortion every time I log in, but since it just opens the GUI it's a bit difficult to do so

**Comment by valadaptive** [comment]
This has been implemented in v0.9.0!
