### ISSUE TITLE
Random Flickering in the UI

### ISSUE THREAD

**Issue by Akascape** [valadaptive/ntsc-rs#83]
I found a bug in the UI of ntsc-rs, there are some random flickers happening in the window when I try to move, hover my mouse over it.

Here is the video:

https://github.com/valadaptive/ntsc-rs/assets/89206401/f6b7245e-5eaf-4fe7-b9e9-8b78fa50c9c5

However, the issue gets fixed when we resize the window. 

(Also add a minimum resize width/height for the window)

**System Specs:** 
Windows 11 Pro 22631.3527
AMD Processor

**Comment by valadaptive** [comment]
This may be an issue with your graphics card or graphics driver. What graphics card are you using, and do you run into any similar issues running 3D games?

**Comment by Akascape** [comment]
@valadaptive I am currently using radeon graphics, maybe this is some internal issue with the base libraries of the app.

**Comment by valadaptive** [comment]
> I am currently using radeon graphics

Can you be more specific on what model of graphics card you have, whether you've installed the *latest* official AMD drivers for it, and whether other 3D games or applications also flicker? Please answer all three questions. You should be able to determine the model in Device Manager. 

I suspect you *might* need to file this as an upstream bug in egui. The issue you linked to is about the `egui_glium` rendering backend, but I use the default `egui_glow` rendering backend.

**Comment by valadaptive** [comment]
@Akascape Is this still an issue? If so, what model of GPU do you have, do any other 3D games or applications also flicker, and have you tried updating the GPU drivers?

**Comment by valadaptive** [comment]
Closing this issue due to a lack of activity. Let me know if you're still having issues.
