### ISSUE TITLE
Windows thinks the app is frozen whenever it opens an explorer popup

### ISSUE THREAD

**Issue by nexus226** [valadaptive/ntsc-rs#84]
When the standalone app triggers an explorer popup (by opening a file, saving/loading presets) Windows thinks the main window is frozen. You can see it by trying to interact with the main window after a few seconds. It unfreezes instantly when the popup is closed. This doesn't affect normal usage, but it's a problem nonetheless. This might be exclusive to Windows 10 (my OS). It isn't exclusive to the most recent version.

My assumption is (correct me if I'm wrong) that ntsc-rs is waiting for the operation (e.g. picking a file) to complete and Windows is wrongly assuming the app is stuck processing this operation and thus not responding.

**Comment by valadaptive** [comment]
Fix is blocked on https://github.com/PolyMeilex/rfd/pull/191. Might just use my own fork of rfd and push an update; it'll require some testing since there have been more upstream changes

**Comment by valadaptive** [comment]
Fixed in v0.6.2
