### ISSUE TITLE
is it possible to use this on OBS?

### ISSUE THREAD

**Issue by oisintheblue** [valadaptive/ntsc-rs#9]

**Comment by valadaptive** [comment]
I don't currently have plans to make an OBS plugin. I just looked into it and it seems like the plugin API is not forward-compatible, meaning I'd have to update and test the plugin with each new OBS release. I don't have the time to keep up with that kind of release schedule.

If a third party wants to make an OBS plugin, ntsc-rs should be capable of it. It's just a continuous workload to take on.

**Comment by Valephnull** [comment]
ive wanted an OBS plugin, because so far i haven't found a good way to have NTSC-RS applied to my webcam live without hooking 5 applications together

**Comment by AdamIsrael** [comment]
Hi @Valephnull and @oisintheblue. I've created an [obs-ntsc plugin](https://github.com/AdamIsrael/obs-ntsc) that uses ntsc-rs to provide the video effects to OBS sources. It's still fairly early, but it is very functional if you wanted to give it a try. Any feedback is appreciated.
