### ISSUE TITLE
ntsc-rs crashes my computer.

### ISSUE THREAD

**Issue by Oweblow1** [valadaptive/ntsc-rs#91]
This has happened twice now: I'm just using ntsc-rs, then my computer monitor stops displaying a signal from my GPU, my keyboard and mouse's lights turn off (Razer Blackwidow v3 and Deathadder v2) and my PC is completely unreponsive, I can't even hold the power button to power it off, I have to turn it off by the power supply which is incredibly risky. Please fix this: this is a realistic VHS effect and I don't want to have to stop using it so I don't end up frying my PC.

**Comment by 0x5066** [comment]
It's not an ntsc-rs issue and more so with your hardware, more than likely.
I'd check if the same happens with other intensive applications, or bring your computer to a shop, if feasible.

**Comment by Degamisu** [comment]
it could be age, I had it happen to my computer before. Depending on the age of your PC, it wears down and crashes after a while. Just to be safe if its old, backup all your files. I lost a lot of stuff when my PC died. (some recovered though)

**Comment by valadaptive** [comment]
As mentioned above, this is likely a hardware issue. The only software capable of crashing your computer like that is a driver, which ntsc-rs is definitely not.

There are a variety of hardware issues which could cause this.

Your CPU may be overheating (you can check with [Core Temp](https://www.alcpu.com/CoreTemp/); ntsc-rs makes use of all CPU cores, so it can be quite intensive on high-resolution videos.

It could also be a dying GPU--the user interface is GPU-accelerated, and moves a lot of data onto the GPU during video playback. This sounds like the most likely culprit to me. You can try running some GPU-intensive games and see if you get similar crashes.

**Comment by Oweblow1** [comment]
My computer's hardware is an AMD Radeon RX 6700 XT and an AMD Ryzen 5900x (other hardware included obviously but isn't important here). The computer itself (considering upgrades overtime) is technically 5 months old. The idea that it happens when my PC experiences intense usage is wrong, as (here is an example) I have played GTA V before at just over default settings at 90-180 FPS without it crashing. To be fair, there is a driver update to my AMD Adrenalin software from 24.2.1 to 24.4.1. Do you happen to know any applications that can conflict with ntsc-rs?

**Comment by Oweblow1** [comment]
Oh, and if it helps, I'm running Windows 11 Pro 23H2.

**Comment by Oweblow1** [comment]
And also, even with the driver update, it crashed my PC again so from the looks of things, it's an issue with your software.

**Comment by valadaptive** [comment]
Userspace software *cannot* crash your computer by itself. If it could, that would be a massive security vulnerability. Try running a Blender benchmark or something else to stress your CPU? Or [Memtest86+](https://memtest.org/) to test your RAM?

There may also be some issues with third-party drivers for other hardware. I once installed a driver for a drawing tablet that caused random crashes until I flat-out deleted it because the uninstaller didn't work.

**Comment by Oweblow1** [comment]
If it was an issue, I'd check for ways to fix hardware support issues if you have any.
Any, looking at Event Viewer, it gave "Kernel-Power" errors saying my PC rebooted without shutting down, weirdly, it's even before I started having issues with your software. 🤔 Look, I'm gonna do the stress test thing to check further.
![image](https://github.com/valadaptive/ntsc-rs/assets/169087397/3ffea980-a188-498b-931d-442f203fe51b)

**Comment by 0x5066** [comment]
"weirdly, it's even before I started having issues with your software."
Am leaning towards the PSU being faulty for one reason or other, but do run these tests.

**Comment by Oweblow1** [comment]
Yeah, I'm going to run the Blender Benchmark. By the way, what I meant by the issues is the errors.

**Comment by Oweblow1** [comment]
I ran the Blender benchmark, nothing crazy happened, I just tested my CPU and GPU, it benchmarked both of them and it didn't cause any issues, and I can't run memtest86+ because the only flash drive I have is inside my Wii U. Yeah, it kinda sounds like you're in denial, while it is suspicious that barely anybody else has reported this, it seems to be a problem with your software.

**Comment by Oweblow1** [comment]
![image](https://github.com/valadaptive/ntsc-rs/assets/169087397/4e807807-394e-4c59-ae2f-8f88e5f0e41d)
![image](https://github.com/valadaptive/ntsc-rs/assets/169087397/d01a9d1b-947f-409e-b452-c14373d372c2)
These are the results of the Blender benchmark.

The only thing of some interest that occured during testing is when it was testing the CPU; the cursor started to lag a bit, but I don't consider it an anomaly because the Blender benchmark was literally using 100% of my CPU, of course that's probably going to happen.

Anyway, I didn't use memtest86+ as it asked to be installed to a flash drive, and the only flash drive I own is inside my Wii U.

Also, ever since I've stopped using ntsc-rs (after 8 May 2024), there has been no Kernel-Power errors in Event Viewer which increases my belief that it may be your software that is the issue, I'm sorry.

**Comment by 0x5066** [comment]
> ...because the Blender benchmark was literally using 100% of my CPU...

err, do you have any GPU based benchmarks? The only one I know of that is free is https://benchmark.unigine.com/valley

**Comment by Oweblow1** [comment]
I know of one called Unigine Heaven, I'm gonna test Unigine Valley and that.

**Comment by Oweblow1** [comment]
![Screenshot 2024-05-10 213126](https://github.com/valadaptive/ntsc-rs/assets/169087397/2474264b-880d-4ae2-8222-f022b6901468)
![image](https://github.com/valadaptive/ntsc-rs/assets/169087397/877c8766-affb-4d0f-a89e-b2102d7bb7f6)
I did both benchmarks at the highest settings (Extreme and Extreme HD for Unigine Valley), and sorry to say amigo but it appears to be your software. My PC didn't break a sweat in both of these benchmarks for the most part (at default clockspeed), it only got 70 degrees celsius hot because y'know: intense rendering. Look I'm sorry, ok?

**Comment by Oweblow1** [comment]
If it was a problem relating to the power supply, I would've found out in both benchmarks as it would've probably had some pretty bad issue doing it. Look man, I'm sorry to burst your bubble, ok?

**Comment by valadaptive** [comment]
I fully believe that ntsc-rs is *triggering* the bug, but it is not a bug in ntsc-rs itself. This is because *the OS is designed not to allow individual applications to crash it*. If an application can find a way to crash the OS, it's a very big security vulnerability, and Microsoft will pay you a lot of money for finding it.

It's like if I went to lean against the side of a building, and the entire thing collapsed. Yes, the building's collapse was caused by me leaning on it, but *buildings shouldn't do that*.

Back in the olden days, the operating system ran on the same level as all the applications, and they were all expected to play nicely with each other. If one application crashed, it would bring down the whole system.

Nowadays, all operating systems run at a lower level than the applications do, which isolates badly-behaving applications from one another. If an app is using 100% CPU, the OS will simply say "sorry, it's not your turn with the CPU anymore" and give the next application time to run. If an app freezes in Windows, it'll just say "this application is not responding" rather than your entire *computer* not responding.

The only software that runs on the same level as the OS is device drivers, which may be causing the issue.

Another possibility is an issue with the CPU--some people have reported issues with the Ryzen 5900X:
- [Ryzen 5900x: System constantly crashing/restarting WHEA-Logger ID 18 and critical error Kernel-Power](https://community.amd.com/t5/processors/ryzen-5900x-system-constantly-crashing-restarting-whea-logger-id/td-p/423321)
- [AMD Ryzen 9 5900X mce Hardware Error ](https://www.reddit.com/r/linuxhardware/comments/nsqz2l/amd_ryzen_9_5900x_mce_hardware_error/)
- [My PC crashes since I upgraded to a Ryzen 9 5900x](https://www.reddit.com/r/AMDHelp/comments/y6j7db/my_pc_crashes_since_i_upgraded_to_a_ryzen_9_5900x/)

You could try disabling PBO (CPU overclock), D.O.C.P./XMP (RAM overclock), and/or upgrading your BIOS.

**Comment by Oweblow1** [comment]
Actually, I've never overclocked the CPU or RAM, and way before I started experiencing issues, I flashed my BIOS to the latest version.

**Comment by Oweblow1** [comment]
Also, it's not as if my PC was frozen, my mouse just started to lag (like from 180 fps to 20-40 fps).

**Comment by valadaptive** [comment]
PBO and D.O.C.P may be enabled by default.

> Also, it's not as if my PC was frozen, my mouse just started to lag (like from 180 fps to 20-40 fps).

Wait, your mouse lags when doing what exactly?

**Comment by Oweblow1** [comment]
The Blender benchmark.

**Comment by Oweblow1** [comment]
In CPU mode.

**Comment by Oweblow1** [comment]
![Uploading Screenshot 2024-05-10 205044.png…]()

**Comment by Degamisu** [comment]
> The Blender benchmark.

What version of blender are you using for the benchmark?

**Comment by 0x5066** [comment]
We're not really getting anywhere...
>PBO and D.O.C.P may be enabled by default.

This should be investigated, though

**Comment by Oweblow1** [comment]
I don't want to use ntsc-rs again to crash my PC because well... do I even have to explain the riskiness of doing that?

**Comment by valadaptive** [comment]
> However, I can say this guy was having exactly the same issue (same thing happened). #48

As I mentioned in that other issue, an application crash that happens predictably (when the render button is pressed) is different from an OS crash that happens randomly. Not all crashes are the same.

As I have mentioned many times, an application that isn't a driver and doesn't even ask for admin permissions *cannot* crash the OS on its own. There *must*, by definition, be a bug in the OS or a hardware issue, because one of the OS's core responsibilities is to *prevent* applications from crashing your entire computer.

**Comment by Oweblow1** [comment]
In that case, your program is starting to sound like an undetected virus that somehow silently got admin permissions.

**Comment by Oweblow1** [comment]
Or who knows, maybe Windows 11 is actually that bad.

**Comment by valadaptive** [comment]
> In that case, your program is starting to sound like an undetected virus that somehow silently got admin permissions.

If I knew how to bypass the UAC prompt and obtain enough permissions to crash the OS, I would have a lot of bug bounty money from Microsoft.

Seeing as many people have used this very same software on Windows and I haven't received any other reports of OS crashes, I really do not see any other possibility than something being wrong with your computer.

Try the following, and see if they make any difference:
- Reboot into safe mode and try running ntsc-rs there, to rule out potential driver issues.
- Ensure that Precision Boost Overdrive is **Disabled** in your BIOS.
- Ensure that EXPO/XMP is **Disabled** in your BIOS and that your RAM is running at **2133MHz**. (the 5900X uses DDR4, right?)

**Comment by Degamisu** [comment]
> Or who knows, maybe Windows 11 is actually that bad.

No. Windows 11 is supported and tested.


> In that case, your program is starting to sound like an undetected virus that somehow silently got admin permissions.

This is mostlikely the case. is your antivirus `avira` by any chance?

**Comment by Oweblow1** [comment]
No, it's Malwarebytes, and besides, I scanned the app file with VirusTotal- wait, are you saying yourself that your own application is a virus?

**Comment by Oweblow1** [comment]
@valadaptive There's no PBO support in my BIOS I believe, I'll check the rest.

**Comment by valadaptive** [comment]
@Degamisu is not affiliated with this project in any way. I think she may have had some issues with Avira in the past, and/or is suggesting that some other virus might be causing the problem.

**Comment by Oweblow1** [comment]
Ok, thing is, I've scanned my PC with Malwarebytes and there is no malware.

**Comment by Oweblow1** [comment]
![Uploading IMG_20240518_155058005_HDR.jpg…]()
Wait, is this supposed to be PBO?

**Comment by Oweblow1** [comment]
WAIT, I've found PBO, I disabled it, now let me try the software to see if there's any problems.

**Comment by Oweblow1** [comment]
@valadaptive Oh my god, thank you so much! I'm so sorry for ever doubting you! Turns out PBO just had to be disabled!

**Comment by Oweblow1** [comment]
May God bless you (if he's real).

**Comment by Oweblow1** [comment]
Oh wait, it crashed again, nevermind.

**Comment by Oweblow1** [comment]
Went into Safe Mode: ntsc-rs didn't even launch (kept getting this error saying ctrmon.exe overflow).
Went into the BIOS: XMP didn't seem to be enabled, the RAM was running at it's default clockspeed (DDR4-2666).

I think it might be a driver issue, I'll reinstall my graphics card driver in safe mode to make sure.

**Comment by Oweblow1** [comment]
I reinstalled the driver, I've also disabled fast startup (because it's known to cause the Kernel-Power error), time to test it.

**Comment by Oweblow1** [comment]
I've rendered 10 videos as a test to make sure it doesn't end up crashing, and no problems have occured. Thank you so much @valadaptive and again, sorry for ever doubting you.

**Comment by Degamisu** [comment]
> @Degamisu is not affiliated with this project in any way. I think she may have had some issues with Avira in the past, and/or is suggesting that some other virus might be causing the problem. I don't personally think that's likely.

Yes, Avira has fried one of my computers, the symptoms @Oweblow1 was reminding me of the symptoms (, which could get more serious if it were the case.

anyways, glad the issue is fixed!

**Comment by Oweblow1** [comment]
@Degamisu I wouldn't really trust Avira, if you ever need anti-malware, use Malwarebytes to scan your PC (only let it run when you want to do a system scan to stop the pop-ups) and use VirusTotal to scan downloaded files off the internet.

**Comment by Degamisu** [comment]
> @Degamisu I wouldn't really trust Avira, if you ever need anti-malware, use Malwarebytes to scan your PC (only let it run when you want to do a system scan to stop the pop-ups) and use VirusTotal to scan downloaded files off the internet.

Thanks! I use a combination of Avast and my own custom antivirus. Thanks for the suggestion though!

**Comment by Oweblow1** [comment]
Wait, custom antivirus?

**Comment by Oweblow1** [comment]
@valadaptive It happened again.

**Comment by Degamisu** [comment]
> @valadaptive It happened again.

now that its fresh in your mind, was there any bluescreen?

**Comment by 0x5066** [comment]
If a Bluescreen occurred, this will be useful:
https://www.nirsoft.net/utils/blue_screen_view.html

**Comment by valadaptive** [comment]
If disabling PBO *decreases* the crash rate, it's possible that something's wrong with your CPU or RAM. I know you already ran the Blender benchmark, but try [Prime95](https://www.mersenne.org/download/#stresstest) or purchase a USB drive and try memtest86.

**Comment by Oweblow1** [comment]
@Degamisu @0x5066 A bluescreen didn't occur.

**Comment by Oweblow1** [comment]
@valadaptive Welp, if you say so.

**Comment by Oweblow1** [comment]
@valadaptive Um... are you sure this is safe to execute?
![image](https://github.com/valadaptive/ntsc-rs/assets/169087397/8ad44b71-b9d0-48b8-8a5b-949603e4bde3)

**Comment by Oweblow1** [comment]
I'm gonna execute it, most security vendors didn't detect anything malicious anyway.

**Comment by valadaptive** [comment]
Yes--a 1/67 on VirusTotal is likely to occur for many applications. False positives happen, and when you multiply a false positive rate by the 67 different antiviruses that VirusTotal uses, it goes way up.

**Comment by Oweblow1** [comment]
What tests should I try with Prime95?

**Comment by Oweblow1** [comment]
Still waiting for a response.

**Comment by valadaptive** [comment]
Try the "Blend" test?

**Comment by Oweblow1** [comment]
Okeli dokeli.

**Comment by Oweblow1** [comment]
To be honest, for the most part, ntsc-rs works fine, ever since this message
> @valadaptive It happened again.
it's only happened once, I guess I just shouldn't render videos with it unless I have to.

**Comment by Oweblow1** [comment]
Here's a couple videos I rendered with it (I really like the effect, nice work):
https://www.youtube.com/watch?v=kZVTlh9qKEI
https://www.youtube.com/watch?v=MAlzuavD0gE
https://www.youtube.com/watch?v=8RKjyHgwX2E
https://www.youtube.com/watch?v=c2mSAReJgBM
https://www.youtube.com/watch?v=KjtuWWW5o0U
https://www.youtube.com/watch?v=J_n2CiOGEIE

**Comment by Oweblow1** [comment]
@valadaptive Ok, it's been some time since I've last talked about this. Ever since then, it has crashed more times on my PC so I stopped using it there. I've only been using it on my laptop (Acer Aspire A715-72G with upgraded 20 GB RAM and M.2 drive) and it has worked fine with no crashing.

I did try the blend test when you told me to, alongside now; it doesn't seem to impact anything while I'm using my PC (general activity).

I'd keep using it on my laptop but the setup is so janky having to transfer videos from my PC to my laptop, and the preview looks messed up.

So what now?

**Comment by valadaptive** [comment]
You could try the OpenFX version with Davinci Resolve or Vegas to see if that helps things at all. Other than that, I don't think there's much else you can do. I can't reproduce this issue at all, and the fact that it crashes your entire computer and seems to work fine on a different machine points to it being a hardware issue.

I'm experiencing something similar right now with my own PC--GPU-intensive tasks (like playing certain video games) will cause my PC to immediately reboot if done for long enough periods. I haven't tracked down the component responsible, but I also have a Ryzen CPU (a 7700X, so a generation newer than yours). I think that my issue is also something to do with hardware, and I may report back if I can track down what it is.

**Comment by Oweblow1** [comment]
I take it mine's was suppposed to reboot everytime it crashed but it didn't.
Ok, I'll try the OpenFX version then.

**Comment by Oweblow1** [comment]
openfx.org?

**Comment by 0x5066** [comment]
https://github.com/valadaptive/ntsc-rs/releases/tag/v0.8.0

**Comment by Oweblow1** [comment]
I'm dumb, I'm dumb. K, I'm gonna download DaVinci Resolve because Vegas sucks and it gives me an opportunity to possibly try out a better video editor.

**Comment by Oweblow1** [comment]
![image](https://github.com/user-attachments/assets/0b0a7b28-24e6-4b1e-bd7e-55b3b469146d)
Huh, I don't remember it crashing on me: keep in mind, I wasn't using your software.

**Comment by Oweblow1** [comment]
@valadaptive Ok, I didn't bother downloading the OFX plugin. But, I searched up the issue and apparently, it crashing during GPU-intensive stuff seems to be an issue relating to possible insufficient voltage (possibly relating to RAM). Besides, the default voltage on a Ryzen motherboard doesn't seem to reach that amount: the person with the solution mentioned overclocking the RAM to 1.4 volts to solve the insufficient voltage.

Alongside that, the ram on my PC wasn't running at it's full speed (doing DDR4-2666 when it supports DDR4-3200), so that may have been an issue.

I'm gonna do some testing with your software now to see if it crashes for a bit.

**Comment by Oweblow1** [comment]
So far, it's been working fine.

**Comment by Oweblow1** [comment]
Still workin' fine.

**Comment by Oweblow1** [comment]
Yep, that's the fix. @valadaptive I'd recommend in your case either bumping up the RAM voltage to 1.4 V, or possibly getting a new PSU (your's could potentially be faulty).
