### ISSUE TITLE
After Effects error: internal verification failure, sorry! {Bad parameter to PFp_SuiteGetPixelFormat()}

### ISSUE THREAD

**Issue by DrFalamin** [valadaptive/ntsc-rs#93]
Hey, I'm getting this error on After Effects 2023 (23.6). It's not crashing, it just shows this window time to time but it's a bit annoying and I already tried to purge memory and disk cache.
Edit : It shows everytime I change a setting
![image](https://github.com/valadaptive/ntsc-rs/assets/42572851/a69b657a-ec5d-473a-bb57-32efbe4ca6a2)

**Comment by valadaptive** [comment]
I can't reproduce this in After Effects 23.6.2 and version 0.6.2 of the effect (1.4.0 in the "About" dialog).

What version of After Effects (including the patch version) and the effect are you using? Does this happen across all clips or only some?

**Comment by DrFalamin** [comment]
I'm using After Effects 23.6 build 62 and I tried all versions from 0.6.0 to 0.6.2. And it happens to all clips even when I just add a solid on my composition.

**Comment by valadaptive** [comment]
Just 23.6? No 23.6.0 or any point-release like that?

I'm running 23.6.2 build 5:
![image](https://github.com/valadaptive/ntsc-rs/assets/79560998/c14585b4-bc58-410d-9a3a-4fb7c3d31a02)

I can think of a few possibilities for what's going on:
- The ABI for plugins on your copy of AE is somehow different than what my plugin expects. If this was the case, I'd expect it to happen with other plugins as well, or to happen on my copy of AE too.
- Some third-party plugin is causing memory corruption within AE. Do you have any other plugins installed that don't come with AE?
- Something's wrong with your copy of AE. Maybe try upgrading it or running an older edition?

**Comment by DrFalamin** [comment]
Yup, mines just 23.6. I'll try maybe with another edition because it worked perfectly fine until I downgraded to 23.6 (I had some issues with another version)

**Comment by DrFalamin** [comment]
Update : Issue fixed. I installed AE 2024 not knowing it was 2024, so when I saw, I uninstalled it and went back to the 2023 (I didn't uninstall it). I continued editing and noticed that I hadn't the bug anymore lol. Thanks for your help anyways @valadaptive
